DB構築-users&orders関連の実装[nakaji]
quest-academia/qa-laravel-ec-training pull request #10
Opened 2021-01-16 01:45 UTC by paleo-engineer

・1/10〜のタスクである「DB構築-users関連」「DB構築-orders関連」の実装を行いました。
・商品テーブルとの外部キー制約は、個人での動作確認時はコメントアウトしましたが、これは元に戻した状態です。
・Migrationファイルのデータ型(特にDeleteフラグ等)あたりに自信が無いので、ご確認いただけたら幸いです。
よろしくお願いいたします！

2021-01-16 01:52 UTC, paleo-engineer commented on database/migrations/2021_01_11_015700_create_m_users_table.php
> +            $table->integer('delete_flag')->nullable()->comment('deleteフラグ');
deleteフラグはこの書き方で合っていますでしょうか..？
これはあとでユーザーの論理削除の機能で使うものになるものと思いますが、
その場合「SoftDelete」などの記述が必要なのでしょうか？

アドバイスをお願いいたします..!!

2021-01-17 00:57 UTC, KyoheiYamamoto commented on database/migrations/2021_01_11_015700_create_m_users_table.php
> +            $table->integer('delete_flag')->nullable()->comment('deleteフラグ');
ER図確認してみたらと思いますが
char('delete_flag', 1)->default(0)の方が良いかと個人的には思います

2021-01-17 00:58 UTC, KyoheiYamamoto commented on database/migrations/2021_01_11_020300_create_t_order_details_table.php
> +            $table->foreign('products_id')->references('id')->on('m_products');
コメント欄でメモを残すのは良いですね〜

2021-01-17 01:00 UTC, KyoheiYamamoto commented on database/seeds/MUsersTableSeeder.php
> +            'email' => Str::random(10) . '@gmail.com',
このやり方さすがですっていう感じですね〜
あえてコードを量を少しでも減らす工夫されている姿勢はとても大事ですよ！！

2021-01-17 01:11 UTC, KyoheiYamamoto commented on database/migrations/2021_01_11_020100_create_t_orders_table.php
> +            // ユーザIDの外部キー制約
ここのコメントは記載不要でも大丈夫ですよ！！

2021-01-17 01:18 UTC, KyoheiYamamoto commented on database/migrations/2021_01_11_020300_create_t_order_details_table.php
> +            $table->foreign('order_id')->references('id')->on('t_orders');
注文はキャンセルする可能生が大いにあるのでここの外部キー制約には
```->onDelete('cascade')``` をつけるのが無難ですね

2021-01-17 01:24 UTC, KyoheiYamamoto commented on database/seeds/MUserClassificationsTableSeeder.php
> +            'user_classification_name' => '個人',
ここのテーブルは登録したユーザー識別を表すので
出品者、購入者、管理者の方がベターですね〜
個人と法人だとAmazonとかだと出品も購入もどっちもできちゃうですよ
seederでも値にその他は個人的にはあまりおすすめしません笑

2021-01-17 01:33 UTC, KyoheiYamamoto requested changes
テーブル作成お疲れ様でした。
テーブルに```->comment```を入れて１手間を入れるあたりは気遣いの面はさすがですね
なかじさんの人柄が出ていました。

現場によりますが//のコメントは残しても良いところとあまり残すなというところが
あるので現場入るときはコメントは残しても良いですか？？
的なことを聞くと良いかもです〜

修正点とかいくつかありますのでご確認くださいませ

2021-01-17 02:33 UTC, paleo-engineer commented on database/migrations/2021_01_11_015700_create_m_users_table.php
> +            $table->integer('delete_flag')->nullable()->comment('deleteフラグ');
ありがとうございます！
データ型はcharにして、default値は0にするということですね。
いただいたように修正いたします。

2021-01-17 02:33 UTC, paleo-engineer commented on database/migrations/2021_01_11_020300_create_t_order_details_table.php
> +            $table->foreign('products_id')->references('id')->on('m_products');
ありがとうございます！
コードを読む人の立場になって書くことをこれからも意識していきます。

そしてコメントの( )内はその理由が明確にわかるように、
「商品テーブルが無い状態でのmigrateテスト時は一時的に無効にすること」に修正しようかと思います。

2021-01-17 02:35 UTC, paleo-engineer commented on database/seeds/MUsersTableSeeder.php
> +            'email' => Str::random(10) . '@gmail.com',
ありがとうございます！
少し工夫した点だったので嬉しいです！
今後もできる限りコード量を減らせないか常に意識したいと思います。

2021-01-17 02:37 UTC, paleo-engineer commented on database/migrations/2021_01_11_020100_create_t_orders_table.php
> +            // ユーザIDの外部キー制約
承知いたしました！
外部キー制約の記述は一行ですし、
「外部キー制約を書いているな」明らかにと分かりますもんね..！

2021-01-17 02:38 UTC, paleo-engineer commented on database/migrations/2021_01_11_020300_create_t_order_details_table.php
> +            $table->foreign('order_id')->references('id')->on('t_orders');
承知いたしました！
そうですね、注文キャンセル時に一緒に削除されなければなりませんね..！

2021-01-17 02:41 UTC, paleo-engineer commented on database/seeds/MUserClassificationsTableSeeder.php
> +            'user_classification_name' => '個人',
ありがとうございます！
なるほど、ECサイトの「ユーザ種別」というものを理解していなかったのですが、
出品者、購入者、管理者が良さそうですね！
個人、法人、そして「その他」はうかつでした..笑
こちら、修正いたします！

2021-01-18 02:19 UTC, KyoheiYamamoto commented
修正している点を確認しました！
外部キーのコメント以外はマイグレーションは私の環境では正常に動いていました！
それと私がmasayukiさんとの兼ね合いてきなものもありますが、seederファイルの名前はMUsersTableSeeder.phpやTOrderDetailsTableSeeder.phpとありますが、最初の大文字MとTを消去した方が統一感あってみやすいかと思いました。
恐れ入りますが、そちらの修正をお願いします

2021-01-18 03:47 UTC, paleo-engineer commented
> 修正している点を確認しました！
> 外部キーのコメント以外はマイグレーションは私の環境では正常に動いていました！
> それと私がmasayukiさんとの兼ね合いてきなものもありますが、seederファイルの名前はMUsersTableSeeder.phpやTOrderDetailsTableSeeder.phpとありますが、最初の大文字MとTを消去した方が統一感あってみやすいかと思いました。
> 恐れ入りますが、そちらの修正をお願いします

上記の件、Seederファイルの名称と各Class名を修正(先頭のMとTを消去)しました！
動作も問題がないことを確認しました！

2021-01-18 13:25 UTC, SekiYukihiro commented on database/seeds/UsersTableSeeder.php
> +            'email' => Str::random(10) . '@gmail.com',
メールが重複しないようにランダムに作られているのはとても良いですね❗️

ただ、下記は修正されなくてOKですが、
細かい点を少しアドバイスだけさせて頂きます😊

論理削除の場合を考えて、メールアドレスをランダムにされたのかなと思うのですが、

ただ、idが 1~3 で指定されていますので、
同じシーダーを２回実行すると、idが重複してしまい、
Eメールの重複以前にエラーとなると思います。

そうなると、メールがランダムになっている意味が薄れてしまうかな、と思いました。

なので、この場合は、
修正しなくてOKですが、idは指定しない方がベストかなと感じます✨

2021-01-18 13:25 UTC, SekiYukihiro commented on database/migrations/2021_01_11_015700_create_m_users_table.php
> +            $table->string('email', 128)->comment('メールアドレス')->unique()->safeEmai;
safeEmailまで使われていて素晴らしいですね！

ただ、最後の「l(エル)」が抜け定ませんか？

2021-01-18 13:25 UTC, SekiYukihiro commented on database/migrations/2021_01_11_015700_create_m_users_table.php
> +            $table->integer('delete_flag')->nullable()->comment('deleteフラグ');
SoftDeleteでも良いのですが、
今回は設計書に沿った今の書き方でOKかと思います😊

2021-01-18 13:37 UTC, SekiYukihiro requested changes
確認しました！

コーディング規約含めて、とても細かい点まで気を遣われていて、
素晴らしい出来だと思いました✨

１つだけ修正をお願いしたい点と、
あとは今後のアドバイスをさせて頂きましたので、
ご確認頂ければと思います！

宜しくお願い致します😊

2021-01-18 13:37 UTC, SekiYukihiro commented on database/seeds/ShipmentStatusesTableSeeder.php
> +        ]);
前にzoomで言っていた繰り返し処理を書くと、
こんな感じです！

こんな感じに書き直してもOKですし、今のままでも全く問題ありません😊
参考までにどうぞ！

```
$shipment_status = ['発送準備中','発送済み','配送中'];
        foreach ($shipment_status as $status) {
            DB::table('m_shipments_statuses')->insert([
                'shipment_status_name' => $status
            ]);
        };
```

2021-01-18 13:38 UTC, SekiYukihiro requested changes
確認しました！

コーディング規約含めて、とても細かい点まで気を遣われていて、
素晴らしい出来だと思いました✨

１つだけ修正をお願いしたい点と、
あとは今後のアドバイスをさせて頂きましたので、
ご確認頂ければと思います！

宜しくお願い致します😊

2021-01-19 14:02 UTC, paleo-engineer commented on database/seeds/UsersTableSeeder.php
> +            'email' => Str::random(10) . '@gmail.com',
ありがとうございます！
Slackでもご回答いただいたように、idは指定しない(書かない)形に修正いたしました！

なおメールアドレスのランダムについては論理削除までは考えていなかったです😉
(ただ論理削除時にはメールアドレスのユニーク制約はうまく解除されるようにしないとなぁとは考えておりました)

2021-01-19 14:03 UTC, paleo-engineer commented on database/migrations/2021_01_11_015700_create_m_users_table.php
> +            $table->string('email', 128)->comment('メールアドレス')->unique()->safeEmai;
ありがとうございます！

これは..凡ミスでした😂
「safeEmai」→「safeEmail」に修正いたしました！

2021-01-19 14:08 UTC, paleo-engineer commented on database/seeds/ShipmentStatusesTableSeeder.php
> +        ]);
ちょうど先日のZoomのMTGでのお話、気になっておりました！
ありがとうございます！

foreach文でのinsert、美しいですね✨
状態や属性を定義するだけのテーブルである、
'm_shipment_statuses'テーブルと'm_user_classifications'テーブルを対象に、
上記のコードを参考に変更いたしました！

2021-01-19 15:10 UTC, KyoheiYamamoto approved these changes

2021-01-20 22:34 UTC, SekiYukihiro approved these changes
お疲れ様でした！

指摘の内容を全て反映されて、
完璧だと思いました😊

コンフリクトについても実務だと頻繁に起こり得ますので
慣れていって頂ければいいと思います！

引き続き宜しくお願い致します。

2021-01-20 22:34 UTC, merged