add:ユーザ情報照会
quest-academia/qa-laravel-ec-training pull request #12
Opened 2021-01-16 06:02 UTC by daichi1123

フロント　ユーザ情報照会を作成終了いたしましたので、確認よろしくお願いいたします！

2021-01-17 04:28 UTC, ykykmumu reviewed
一点だけコメントしました！
気になったのが、m_products_tableはどなたが作成されましたか？
以下の箇所が原因でマイグレーションできなかったので、もし分かれば原因と解決お願いします！

  $table->foreign('user_id')
                    ->references('id')
                    ->on('m_users')
                    ->onDelete('cascade');

2021-01-17 04:28 UTC, ykykmumu commented on resources/views/commons/header.blade.php
> +            <li class="nav-item list-inline-item"><a href="{{ action('UsersController@show') }}" class="nav-link">ユーザー情報</a></li>
コントローラに処理を渡している意図って何かありますか？
ブラウザでは正しく遷移するので問題ないですが、そのまま/users/usersって書いても良いのかなと思いました。

2021-01-17 07:14 UTC, daichi1123 commented on resources/views/commons/header.blade.php
> +            <li class="nav-item list-inline-item"><a href="{{ action('UsersController@show') }}" class="nav-link">ユーザー情報</a></li>
こちらに関してましては、意図はありませんが、どのコントローラのどのアクションを使っているかを明記するものだと思いこの記述にしておりました！

2021-01-17 23:26 UTC, ykykmumu commented on resources/views/commons/header.blade.php
> +            <li class="nav-item list-inline-item"><a href="{{ action('UsersController@show') }}" class="nav-link">ユーザー情報</a></li>
なるほど、処理速度的にコントローラー挟まない方が良いのかなとか思いましたが、ここはどっちが良いのか第二レビューアーの意見を踏まえてから修正しましょうか。

2021-01-17 23:26 UTC, ykykmumu approved these changes

2021-01-18 00:09 UTC, SekiYukihiro requested changes
確認しました！
細かい点だけ修正お願い致します。

あと、今updateなどはコメントアウトされていますが
次回からは、これくらいのコード量なら一度にプルリク出してもらって大丈夫ですよ。

showメソッド指定しているところは、
処理速度はほぼ変わらないと思いますので、
このままでいきましょう。

原則は、プロジェクト内で統一すべきですが
、むしろ、/usersと書くより、拡張性が高くていいと思いますよ！
URLは後々書き換えられて変わってしまう可能性が結構ありますので。

2021-01-18 00:09 UTC, SekiYukihiro commented on resources/views/commons/header.blade.php
> +            <li class="nav-item list-inline-item"><a href="{{ action('UsersController@show') }}" class="nav-link">ユーザー情報</a></li>
showメソッド指定しているところは、
処理速度はほぼ変わらないと思いますので、
このままでいきましょう。

原則は、プロジェクト内で統一すべきですが
、むしろ、/usersと書くより、拡張性が高くていいと思いますよ！
URLは後々書き換えられて変わってしまう可能性が結構ありますので。

2021-01-18 08:03 UTC, daichi1123 commented
UsesController.phpの修正完了いたしましたよろしくお願いいたします！
後、web.phpのなかのupdateのコメントアウトの件了承いたしました！

2021-01-18 13:45 UTC, SekiYukihiro approved these changes
OKです！

問題ないので、マージ致しますね😊

引き続き、ご不明点などあれば、おっしゃってください。
宜しくお願い致します！！

2021-01-18 13:45 UTC, merged