商品周りのMigrationファイル、Seedデータの作成
quest-academia/qa-laravel-ec-training pull request #143
Opened 2021-09-08 15:08 UTC by SugawaraAyaka

★実装内容(What)  
商品周りのMigrationファイル、Seedデータの作成

★編集したこと(Why)  
Migrationファイル、Seedデータの作成をしました。

★テスト証跡  
phpMyAdmin
http://192.168.33.11:8080/index.php?route=/sql&server=1&db=laravel&table=m_products&pos=0
にてテーブルが作成されているかを確認、外部キー制約も確認済み

★再現手順

1. http://192.168.33.11:8080/index.php?route=/sql&server=1&db=laravel&table=m_products&pos=0へアクセス
2. テーブルができているか確認
3. 外部キー制約確認

★レビュワーに考慮してほしいこと  
コードのレビューをお願い致します。

★補足  
'order_date'とpurchas_dateはユーザーが
今現在いないためコメントアウトしています。

2021-09-09 08:12 UTC, KyoheiYamamoto requested changes
動作確認しようとしたらシーディングでエラーが出ていたのでご自身の環境でも確認してみてください・・
あと、Seederファイルの命名規則がバラバラだったのでそちらの修正もよろしくお願いいたします🙇‍♂️

2021-09-09 08:12 UTC, KyoheiYamamoto commented on database/seeds/DatabaseSeeder.php
> +        $this->call(Sale_statusesTableSeeder::class);
Seederの命名規則がバラバラですね・・・
なるべくファイル名の命名規則は統一するようにお願いします🙇‍♂️
https://inouelog.com/laravel-naming-convention/#toc5

2021-09-10 16:44 UTC, SugawaraAyaka commented on database/seeds/DatabaseSeeder.php
> +        $this->call(Sale_statusesTableSeeder::class);
変更しています。ご確認お願い致します。
シーディングでエラーについてはpullする前は自分の環境でしっかりとまわせていましたので、
エラー文を確認したところcomposer dump-autoloadが出てきたので実行したのみになります。
よろしくお願い致します。

2021-09-12 12:33 UTC, daichi1123 requested changes
難しい部分の実装お疲れ様です！
すごくよく書かれていると思います！

細かい部分も指摘させていただきご面倒だとは思いますが修正お願いいたします🙇‍♂️

2021-09-12 12:33 UTC, daichi1123 commented on database/migrations/2013_09_01_135211_create_users_classifications.php
> -            $table->timestamps();
不必要なスペースの削除いいですね！

2021-09-12 12:33 UTC, daichi1123 commented on database/migrations/2020_09_02_165755_m_sale_statuses.php
> +
もし時間があればこちらのスペースも必要ないので削除しておいてください😄

2021-09-12 12:33 UTC, daichi1123 commented on database/migrations/2020_09_02_163657_create_m_product_statuses_table.php
> +        Schema::dropIfExists('m_product_status');
こちらはテーブルを削除する際に使用される部分で`dropIfExists('m_product_status')`の丸括弧内のテーブル名を削除するので**16行目**のテーブル名と同じ名前を記述しておきましょう😄

2021-09-12 12:33 UTC, daichi1123 commented on database/migrations/2020_09_02_165755_m_sale_statuses.php
> +        //
`Schema::dropIfExists('テーブル名');`と記述お願いします😄

2021-09-12 12:33 UTC, daichi1123 commented on database/migrations/2022_09_02_150158_create_t_orders_details.php
> +            $table->biginteger('products_id')->comment('商品ID')->unsigned();
変更ありがとうございます！

2021-09-12 12:33 UTC, daichi1123 commented on database/migrations/2022_09_02_150158_create_t_orders_details.php
> +                ->onDelete('cascade');
外部キー制約の追加ありがとうございます！！

2021-09-12 12:33 UTC, daichi1123 commented on database/seeds/PurchasesTableSeeder.php
> +                // 'purchase_date'     => '2021-05-13 12:30:30',
コメントアウトを外しても動作確認できましたのでお手数ですがコメントアウトを外すのをお願いいたします。

2021-09-12 12:33 UTC, daichi1123 commented on database/seeds/PurchasesTableSeeder.php
> +                // 'purchas_date'      => '2021-09-05 12:30:30',
コメントアウトを外しておいてください🙇‍♂️
`purchase`の綴りが間違っているので修正お願いいたします🙇‍♂️
43, 52, 62, 72, 82, 92, 102, 112行目のシーダーデータも`purchas_date`と綴りが間違っているのでコメントアウト外すのと一緒に修正お願いいたします🙇‍♂️

2021-09-12 14:55 UTC, daichi1123 approved these changes
お疲れ様です！
動作確認できました！難しかったと思いますが、この調子で頑張っていってください！

2021-09-13 07:29 UTC, KyoheiYamamoto approved these changes
こちら問題ないので承認します

2021-09-13 07:29 UTC, merged