商品検索、カテゴリー検索ができるようにしました
quest-academia/qa-laravel-ec-training pull request #144
Opened 2021-09-15 14:20 UTC by SugawaraAyaka

★実装内容(What)  
・商品検索機能実装
・カテゴリー検索実装

★編集したこと(Why)  
商品検索とカテゴリー検索をできるようにしました。

★テスト証跡  
①http://192.168.33.11/productsにアクセス
②商品検索で商品が表示されるか確認（曖昧検索も確認済み）
③カテゴリーのみの検索で検索したカテゴリーの一覧が表示されるかを確認
④商品、カテゴリー合わせて検索をかけた場合の表示も確認

★再現手順

1.http://192.168.33.11/productsへアクセス
2. 商品検索に任意の文字を入力し、検索ボタンを押す
3. ２と同様にカテゴリーを選択し、検索ボタンを押す
4. 表示確認済み

★レビュワーに考慮してほしいこと  
コードのレビューをお願い致します。

★補足  
特になし

2021-09-16 13:50 UTC, daichi1123 requested changes
難しい処理の部分の実装お疲れ様です！

修正していただき部分があるのでそちらの修正よろしくお願いいたします！

2021-09-16 13:50 UTC, daichi1123 commented on app/Category.php
> +    protected $table = 'm_categories';
しっかりとテーブルのオーバライドされており素晴らしいですね！

2021-09-16 13:50 UTC, daichi1123 commented on app/Http/Controllers/ProductsController.php
> +    }
とても難しい実装部分お疲れ様です！

2021-09-16 13:50 UTC, daichi1123 commented on resources/views/products/search.blade.php
> +            @endforeach
こちらの部分レイアウト崩れてしまっているので、修正お願いします！

2021-09-16 13:50 UTC, daichi1123 commented on resources/views/products/search.blade.php
> +                <input type="text" class="form-control" name="product_name" value="">
`value=""`は使用されない場合削除しておきましょう！

2021-09-16 15:29 UTC, daichi1123 approved these changes

2021-09-16 15:29 UTC, daichi1123 commented
お疲れ様です！

動作確認OKですので、こうへいさんのレビューをお待ちください！

2021-09-17 04:52 UTC, KyoheiYamamoto reviewed
一部コメント入れておりますのでご確認ください

2021-09-17 04:52 UTC, KyoheiYamamoto commented on app/Http/Controllers/ProductsController.php
> +        ]);
【シカトしてください】
ここの部分このやり方もありますが、一例としてcompact関数っていうやり方もあります
渡す変数が多くない時とからcompactを使うと良いです
https://qiita.com/ryo2132/items/63ced19601b3fa30e6de

2021-09-17 04:52 UTC, KyoheiYamamoto commented on resources/views/products/search.blade.php
> +    <form method="get" action="{{ route('search.products') }}">
csrf対策がされていないすね・・・・
このまｍだとヤバい気がします笑

2021-09-17 04:52 UTC, KyoheiYamamoto commented on resources/views/products/search.blade.php
> +                    @foreach($categories as $id => $category_name)
$idってあとから振り返った時にわかりにくいのな何のIDかを書いた方が良いです🙆‍♂️
あと変数名はなるべくロウワーキャメルケースで記載お願いしますmm
$categoryNameとか

2021-09-17 13:13 UTC, KyoheiYamamoto approved these changes

2021-09-17 13:13 UTC, merged