Feature/daichi/change info
quest-academia/qa-laravel-ec-training pull request #16
Opened 2021-01-22 10:52 UTC by daichi1123

ユーザ情報修正完了いたしました。
バリデーションの設定によりいくつかテーブルとシーダファイルに変更させていただきました。

お手数ですが、確認よろしくお願いいたします！
daichi

2021-01-23 17:24 UTC, ykykmumu reviewed
お疲れ様でした！
動作確認しましたが、修正・削除機能がしっかりと実装されていて素晴らしいと思います。
一点だけ、/users/edit/1の数字をURLから書き換えると他のユーザーの情報を編集できてしまいます。ここを少し考えて実装してもらっても良いですか？

コードに関してはもっといい書き方などがあるかもしれないので、今一度確認しておきますが、一旦これでお返しします。

2021-01-23 17:24 UTC, ykykmumu commented on app/Http/Controllers/UsersController.php
> +    public function __construct(User $user)
コンストラクタは関数の一番最初で定義されていることが多いので14行目あたりがいいですかね。

2021-01-24 18:32 UTC, daichi1123 commented
修正いたしました！
お手数ですが、確認よろしくお願いいたします！

2021-01-25 14:48 UTC, ykykmumu reviewed
伝え方が悪かったのですが、よければ演算子直してみてください！
２次レビューのあと一気にでもいいかもです

2021-01-25 14:48 UTC, ykykmumu commented on app/User.php
> +        select([
伝え方が悪かったかもですが、お伝えしたイメージとしては
 $query = $this
 ->select([
こういう感じでした。
ここについてコーディング規定に乗っていたわけではないのでこれが正解というわけではないかもですが、僕の現場ではこう書いてます

2021-01-25 14:48 UTC, ykykmumu commented on app/User.php
> +        where([
上と同じ

2021-01-25 14:48 UTC, ykykmumu commented on app/User.php
> +        where([
上と同じ

2021-01-25 14:48 UTC, ykykmumu commented on app/User.php
> +        update([
上と同じ

2021-01-25 21:19 UTC, SekiYukihiro requested changes
確認しました！

モデルへのメソッドの切り出しまでできていて、
とてもレベルが高いと思いました✨

いくつか修正して欲しい部分がありますので、
お手数ですがご確認お願い致します！

2021-01-25 21:19 UTC, SekiYukihiro commented on app/Http/Controllers/UsersController.php
> +        User::find($id)->delete();
ここの削除処理に関しても、
念のため、悪意のあるユーザが勝手に自分以外のユーザデータを消すことがないように
if (\Auth::id() == $id)  {
}
で囲っておきましょう。

とはいえ、かなりイレギュラーなケースではあるため、
自分以外のユーザデータを削除しようとした場合の処理（フラッシュメッセージを出すなど）は
記述せず、if文のみの記述でOKかと思います。

2021-01-25 21:19 UTC, SekiYukihiro commented on app/Http/Controllers/UsersController.php
> +        $this->user->updateUserInfo($user);
ここの削除処理に関しても、
念のため、悪意のあるユーザが勝手に自分以外のユーザデータを書き換えることがないように
if (\Auth::id() == $id)  {
}
で囲っておきましょう。

とはいえ、かなりイレギュラーなケースではあるため、
自分以外のユーザデータを変更しようとした場合の処理（フラッシュメッセージを出すなど）は
記述せず、if文のみの記述でOKかと思います。

2021-01-26 09:12 UTC, daichi1123 commented
修正箇所の修正・コンフリクトの解消完了いたしました！
お手数ですが、確認よろしくお願いいたします！

commitの際の名前は次の検索機能から統一していきます。

あと質問なのですが、テーブルの外部制約がテーブルによってインデントの仕方が違うのですが、どちらに統一するべきでしょう。
どちらかがわかればそちらに統一を検索機能の実装のプッシュの際に修正を入れます。

`$table->foreign('product_id')
                  ->references('id')
                  ->on('m_products')
                  ->onDelete('cascade');`

`$table->foreign('product_id')
->references('id')
->on('m_products')
->onDelete('cascade');`

2021-01-26 14:41 UTC, ykykmumu commented
修正確認しましたのでマージします。
ご質問の件ですが、今回だいちさんが書かれているような形が良いと思います。なので上の例ですかね。

・ファーストコミットの名前はこの間きょへさんが言っていたように【daichi】をつける
・講師のコードレビューに対して、修正しました でいいのでコメントをいれる

この２点次からよろしくお願いします！

2021-01-26 14:41 UTC, ykykmumu approved these changes

2021-01-26 14:42 UTC, ykykmumu approved these changes

2021-01-26 20:15 UTC, SekiYukihiro approved these changes
OKです！

問題ありませんので、マージしました😊
お疲れ様でした！

2021-01-26 20:15 UTC, merged