add:マイグレーションとシーディングを実行(フク)
quest-academia/qa-laravel-ec-training pull request #2
Opened 2020-12-21 09:01 UTC by fuku-git

## 機能追加
3テーブルのマイグレーション・シーディングを実行しました。
( m_users_table , m_users_classifications_table  , m_sales_statuses_table )

PSR-2基準になっていない、不要なコードがあるなど現場基準でPRしていただけると
嬉しいです。また、次回からの注意点なども有りましたら教えていただけると助かります。
ご確認よろしくお願いします！

2020-12-21 14:13 UTC, KyoheiYamamoto commented
@fuku-git 
テーブル作成お疲れ様でした！
僕の方で実際にコマンドを実行したら正常にデータベースに入っていたので
指摘した部分がいくつかありますのでそちらをご確認くださいませ〜

コードフォーマットをPSR-2基準になっていない部分がありますのでそちらについてはVscodeの
拡張機能とかを利用したらPSR-2に設定できるので
次回からはコード整形をすると良いかと思いました。

2020-12-21 21:24 UTC, SekiYukihiro requested changes
確認しました！

とても、よく書けていると思います😊
（よく考えながら作っていただいたのが伝わってきます）

僕の方からは、GitHub上で規約を含めて
細かい点をいくつか指摘させて頂きましたので、
下記をご覧ください。

2020-12-21 21:24 UTC, SekiYukihiro commented on database/migrations/2020_12_17_174532_create_m_users_classifications_table.php
> +            $table->string('user_classification_name',32);
カンマの後には、スペースを入れましょう（PSR-2規約）！

2020-12-21 21:24 UTC, SekiYukihiro commented on database/migrations/2020_12_18_000000_create_m_users_table.php
> +            $table->string('company_name',128);
上記と同じく、カンマの後にはスペースが必要です！

2020-12-21 21:24 UTC, SekiYukihiro commented on database/migrations/2020_12_18_183637_create_m_sales_statuses_table.php
> +            $table->string('sale_status_name',32);
上記と同じく、カンマの後にはスペースが必要です！

2020-12-21 21:24 UTC, SekiYukihiro commented on database/migrations/2020_12_18_183637_create_m_sales_statuses_table.php
>              $table->bigIncrements('id');
他と統一して、bigIncrements ではなく、incrementsにしましょう！
bigIncrements は膨大な数のIDを登録する場合に利用するものなので、
今回はincrementsでも十分かなと思います。

2020-12-21 21:24 UTC, SekiYukihiro commented on database/seeds/SalesStatusesTableSeeder.php
> +        ]);
シーダーは、
１データではなく、３〜５つくらいのデータを入れるようにしましょう。

複数のデータを入れてテストをする中で気づくことも多いので、
テストのためには複数のデータを入れることが大事です！

2020-12-21 21:24 UTC, SekiYukihiro commented on database/seeds/UsersClassificationsTableSeeder.php
> +        ]);
シーダーは、
１データではなく、３〜５つくらいのデータを入れるようにしましょう。

複数のデータを入れてテストをする中で気づくことも多いので、
テストのためには複数のデータを入れることが大事です！

2020-12-21 21:24 UTC, SekiYukihiro commented on database/seeds/UsersTableSeeder.php
> +        ]);
シーダーは、
１データではなく、３〜５つくらいのデータを入れるようにしましょう。

複数のデータを入れてテストをする中で気づくことも多いので、
テストのためには複数のデータを入れることが大事です！

2020-12-21 21:24 UTC, SekiYukihiro commented on database/seeds/SalesStatusesTableSeeder.php
> +
こちら、不要なスペースかと思います。

2020-12-21 21:24 UTC, SekiYukihiro commented on database/seeds/UsersClassificationsTableSeeder.php
> +
こちら、不要なスペースかと思います。

2020-12-21 21:24 UTC, SekiYukihiro commented on database/seeds/UsersTableSeeder.php
> +
こちら、不要なスペースかと思います。

2020-12-21 21:24 UTC, SekiYukihiro commented on database/seeds/UsersTableSeeder.php
> +
こちら、不要なスペースかと思います。

2020-12-21 21:24 UTC, SekiYukihiro commented on database/migrations/2020_12_18_000000_create_m_users_table.php
> +
こちら、不要なスペースかと思います。

2020-12-21 21:24 UTC, SekiYukihiro commented on database/migrations/2020_12_18_000000_create_m_users_table.php
> +
こちら、不要なスペースかと思います。

2020-12-21 23:38 UTC, KyoheiYamamoto commented on database/migrations/2020_12_18_000000_create_m_users_table.php
> +            $table->foreign('user_classification_id')->references('id')->on('m_users_classifications')->onDelete('cascade');
こちら適宜インデントを行いましょう
120文字以上なっているので、適宜改行した方が可読性が向上しますよ！！

2020-12-22 00:02 UTC, fuku-git commented on database/migrations/2020_12_17_174532_create_m_users_classifications_table.php
> +            $table->string('user_classification_name',32);
承知しました！以後、気をつけます！

2020-12-22 00:02 UTC, fuku-git commented on database/migrations/2020_12_18_000000_create_m_users_table.php
> +            $table->string('company_name',128);
承知しました！以後、気をつけます！

2020-12-22 00:02 UTC, fuku-git commented on database/migrations/2020_12_18_183637_create_m_sales_statuses_table.php
> +            $table->string('sale_status_name',32);
承知しました！以後、気をつけます！

2020-12-22 00:04 UTC, fuku-git commented on database/migrations/2020_12_18_183637_create_m_sales_statuses_table.php
>              $table->bigIncrements('id');
承知しました！ありがとうございます！
bigIncrementsとincrementsはID数によって
使い分けるのですね！勉強になります！

2020-12-22 00:06 UTC, fuku-git commented on database/seeds/SalesStatusesTableSeeder.php
> +        ]);
ありがとうございます！複数データを入れて再度pushします！

2020-12-22 00:06 UTC, fuku-git commented on database/seeds/UsersClassificationsTableSeeder.php
> +        ]);
ありがとうございます！複数データを入れて再度pushします！

2020-12-22 00:06 UTC, fuku-git commented on database/seeds/UsersTableSeeder.php
> +        ]);
ありがとうございます！複数データを入れて再度pushします！

2020-12-22 00:07 UTC, fuku-git commented on database/seeds/SalesStatusesTableSeeder.php
> +
承知しました！以後気をつけます。

2020-12-22 00:07 UTC, fuku-git commented on database/seeds/UsersClassificationsTableSeeder.php
> +
承知しました！以後気をつけます。

2020-12-22 00:07 UTC, fuku-git commented on database/seeds/UsersTableSeeder.php
> +
承知しました！以後気をつけます。

2020-12-22 00:10 UTC, fuku-git commented on database/seeds/UsersTableSeeder.php
> +
承知しました！以後気をつけます。

2020-12-22 00:10 UTC, fuku-git commented on database/migrations/2020_12_18_000000_create_m_users_table.php
> +
承知しました！以後気をつけます。

2020-12-22 00:10 UTC, fuku-git commented on database/migrations/2020_12_18_000000_create_m_users_table.php
> +
承知しました！以後気をつけます。

2020-12-22 00:11 UTC, fuku-git commented on database/migrations/2020_12_18_000000_create_m_users_table.php
> +            $table->string('first_name',16);
承知しました！以後気をつけます。

2020-12-22 00:11 UTC, fuku-git commented on database/migrations/2020_12_18_000000_create_m_users_table.php
> +            $table->string('email',128)->unique();
承知しました！以後気をつけます。

2020-12-22 00:12 UTC, fuku-git commented on database/migrations/2020_12_18_000000_create_m_users_table.php
> +            $table->string('company_name',128);
承知しました！以後気をつけます。

2020-12-22 00:12 UTC, fuku-git commented on database/migrations/2020_12_18_183637_create_m_sales_statuses_table.php
> +            $table->string('sale_status_name',32);
承知しました！以後気をつけます。

2020-12-22 00:13 UTC, fuku-git commented on resources/views/welcome.blade.php
> +                    Laravel-共同開発
はい！変更してくださいと動画でありました！

2020-12-22 00:14 UTC, fuku-git commented on config/app.php
> +    'timezone' => 'Asia/Tokyo',
laravel-questで教えていただいたお陰です☺️

2020-12-22 00:14 UTC, fuku-git commented on database/migrations/2020_12_17_174532_create_m_users_classifications_table.php
> +            $table->string('user_classification_name',32);
承知しました！以後気をつけます。

2020-12-22 00:21 UTC, fuku-git commented on app/Providers/AppServiceProvider.php
> +        \Schema::defaultStringLength(191);
Schema::defaultStringLength(191);
文字数制限を191文字にしないとエラーが出るのでこの記述をしていると認識しています。また、デプロイしたときにローカルを同じ文字数にしておかないとSQLSTATEエラーが頻繁に起こったと記憶しています。
(mysqlで文字コードがutf8mb4となっている場合1文字4バイトとなり、文字数制限が191文字までになる)

2020-12-22 00:22 UTC, fuku-git commented on database/migrations/2020_12_18_000000_create_m_users_table.php
> +            $table->foreign('user_classification_id')->references('id')->on('m_users_classifications')->onDelete('cascade');
承知しました！整えて可読性を上げます！

2020-12-22 02:26 UTC, KyoheiYamamoto commented on database/seeds/SalesStatusesTableSeeder.php
> +                'sale_status_name' => '入荷未定',
めちゃくちゃ細かいのですが、
プラスidの順序はid => 1が在庫ありにしたら次反対または対応の意味を表す字を重ねた熟語「在庫なし」に置いた方が良いかなと思います。

2020-12-22 02:50 UTC, KyoheiYamamoto commented on database/seeds/UsersClassificationsTableSeeder.php
> +            ],
user_classification_nameが被っているのはNGですよ！！
ER図のdraw.ioみたら載っていますが、こちらのテーブルは基本的にこちらはユーザーを種別するので全て異なるステータスにしないといけません
またバグの温床につながるので、出品者・購入者・管理者に変更した方が良いですよ

2020-12-22 05:17 UTC, KyoheiYamamoto commented on database/seeds/SalesStatusesTableSeeder.php
> +                'sale_status_name' => '入荷未定',
プラスシーディングの直接入力するなら記載方法はこちらでもあっていますが
https://yu-nocode.com/wp/entry/laravel-quest-2/#i-9

```PHP
DB::table('m_products_statuses')->insert([
  'id' => 1,
  'product_status_name' => '在庫有',
]);
DB::table('m_products_statuses')->insert([
  'id' => 2,
  'product_status_name' => '在庫無',
]);
```
みたいに書いた方が

2020-12-22 05:20 UTC, KyoheiYamamoto commented on database/seeds/UsersClassificationsTableSeeder.php
> +            ],
こちらも同じくこのように書いた方が無難かなと思います
```PHP
DB::table('m_users_classifications')->insert([
      'id' => '1',
      'user_classification_name' => 'ゲスト',
]);
```

2020-12-22 05:22 UTC, KyoheiYamamoto commented on database/seeds/UsersTableSeeder.php
> +        ]);
こちらも同じくこのように書いた方が無難かなと思います
```PHP
DB::table('m_users_classifications')->insert([
      'id' => '1',
      'user_classification_name' => 'ゲスト',
]);
```

2020-12-22 05:26 UTC, KyoheiYamamoto requested changes
私の方でいくつか指摘した部分と修正箇所がありますのでご確認くださいませ
シーディングの同時に動作確認しましたが私の方では問題なく動作しております

2020-12-22 05:49 UTC, SekiYukihiro requested changes
細かい点ですが、一点だけ指摘しましたので、お手数ですが修正願います🤲

2020-12-22 05:49 UTC, SekiYukihiro commented on database/seeds/SalesStatusesTableSeeder.php
> +                'sale_status_name' => '残り5個',
細かいですが、

残り5個

という、限定的な状況は、ステータスにはそぐわないかなと思いました。

残り何個というのは、
数量管理する仕組みを別途用意して表示させるべきかと思います。

2020-12-22 05:49 UTC, fuku-git commented on database/seeds/SalesStatusesTableSeeder.php
> +                'sale_status_name' => '入荷未定',
ありがとうございます！
'在庫有' ,  '在庫無' に変更します！
 '残り5個' , '入荷未定', などはそのまま使用しても問題ありませんか？

また、 'sale_status_name'  を 'product_status_name' に変更するのは
'sale_status_name'  がメンバーに理解しにくいからでしょうか？

2020-12-22 05:53 UTC, KyoheiYamamoto commented on database/seeds/SalesStatusesTableSeeder.php
> +                'sale_status_name' => '入荷未定',
残り5個よりも入荷待ちとかの方が良いですね！
>また、 'sale_status_name' を 'product_status_name' に変更するのは
'sale_status_name' がメンバーに理解しにくいからでしょうか？

あくまでも記述例となっております！！ 'sale_status_name'のままで大丈夫ですよ！

2020-12-22 05:55 UTC, fuku-git commented on database/seeds/SalesStatusesTableSeeder.php
> +                'sale_status_name' => '入荷未定',
分かりました！ありがとうございます！

2020-12-22 06:00 UTC, fuku-git commented on database/seeds/UsersClassificationsTableSeeder.php
> +            ],
被るのはNGなのですね！ということは、
'user_classification_name' に '出品者' ・ '購入者' ・ '管理者' をバラバラに配置すればいいでしょうか？

ただ、そうすると 'id' が5こあるので被ってしまうので 'ゲスト' ともう一つユーザー識別を追加して
'user_classification_name' が全て被らないようにしたらいいでしょうか？

理解力不足で申し訳ないです💦

2020-12-22 06:01 UTC, fuku-git commented on database/seeds/UsersTableSeeder.php
> +        ]);
承知しました！ありがとうございます！

2020-12-22 06:02 UTC, fuku-git commented on database/seeds/SalesStatusesTableSeeder.php
> +                'sale_status_name' => '残り5個',
承知しました！変更します！

2020-12-22 06:23 UTC, KyoheiYamamoto commented on database/seeds/UsersClassificationsTableSeeder.php
> +            ],
>'user_classification_name' に '出品者' ・ '購入者' ・ '管理者' をバラバラに配置すればいいでしょうか？

おっしゃる通りですね！
>ただ、そうすると 'id' が5こあるので被ってしまうので 'ゲスト' ともう一つユーザー識別を追加して
'user_classification_name' が全て被らないようにしたらいいでしょうか？

全てかぶらないようにするのが本分なので思いつかなかったら、もう一つユーザー識別「開発者」とかでも大丈夫ですよ！！（もっと良いものがあればご自由にどうぞ）

2020-12-22 06:53 UTC, fuku-git commented on database/seeds/UsersClassificationsTableSeeder.php
> +            ],
承知しました！ありがとうございます！

2020-12-22 08:23 UTC, KyoheiYamamoto commented on database/seeds/UsersTableSeeder.php
> +        ]);
前のコメントはあくまでも記載例なのでシカトしていただいて構いませんよ！
```PHP
DB::table('m_users')->insert([
       カラムの中身
 ]);
DB::table('m_users')->insert([
       カラムの中身
 ]);
DB::table('m_users')->insert([
       カラムの中身
 ]);
```
みたいな感じで書いてくださいってことですね！
カラムの中身はフクさんが記載しているのをそのままで大丈夫ですよ！！

2020-12-22 08:37 UTC, fuku-git commented on database/seeds/UsersTableSeeder.php
> +        ]);
了解しました！カラムのデータごとに DB::table('m_users')->insert([    ]); で区切るのですね！
カラムの中身は変更せずに上記のように書き直します！

2020-12-22 11:44 UTC, KyoheiYamamoto approved these changes

2020-12-22 11:48 UTC, SekiYukihiro approved these changes

2020-12-22 11:50 UTC, merged