create：商品検索＆商品詳細画面の実装[なかじ]
quest-academia/qa-laravel-ec-training pull request #20
Opened 2021-01-31 00:49 UTC by paleo-engineer

- 商品検索機能を実装し、動作を確認しました。
- ただしページネーションは画面定義書では15件表示でしたが、
今回は動作確認を目的とするため3件表示としています。(ダミーデータがまだ少ないので)
- 併せて各商品詳細を表示する画面も実装しました。
- カートに入れるアクションは未実装です。

よろしくお願いいたします..！

2021-02-01 01:07 UTC, KyoheiYamamoto reviewed
実装お疲れ様でした！
私の方で動作確認したところ
カテゴリーごとに絞れるように実装できていました。
商品の詳細画面もそれぞれの値ごとに正常に表示できていたので
指摘部分と確認事項等があるので確認くださいませ〜

2021-02-01 01:07 UTC, KyoheiYamamoto commented on resources/views/products/detail.blade.php
> +</div>
ここは表示だけということで間違いないですよね？？

2021-02-02 21:18 UTC, SekiYukihiro requested changes
確認しました！

直すところがないくらい、完成度が高いと思います✨

よりよく書くためには・・・という内容のコード例などを書きましたので
ご確認ください❗️

今のままのコードでも全く問題ありませんので、
このままで大丈夫であればこのままマージしますし、
もし書き換えられるということであれば、書き換えていただいてからマージします😊

どちらにされるかご確認の上、ご連絡下さいませ✨

2021-02-02 21:18 UTC, SekiYukihiro commented on app/Http/Controllers/MProductController.php
> +        $select_category_id = $request->select_category_id;
変数名は今回はキャメルケースではなく、スネークケースでいかれますか？

どちらが正解ということはないのですが、Laravelだとキャメルケースを使うことの方が少し多いのと
[Laravel共同開発コードレビュー基準.pdf](https://github.com/quest-academia/qa-laravel-ec-training/files/5914445/Laravel.pdf)
こちらのレビュー基準ではキャメルケースということで書かれています。

プロジェクトで統一すべきだと思いますので、
masayukiさんとどちらにするか決めておいて頂けると良いと思います😊
（現時点でまだmasayukiさんのユーザログイン・登録処理では変数名の定義はなかったかなと思いますので
　なかじさんに合わせて、このままスネークケースでも良いかと思います。）

2021-02-02 21:18 UTC, SekiYukihiro commented on app/Http/Controllers/MProductController.php
> +        }
簡潔かつ考えられてつくられていて素晴らしいですね😊

このままで十分合格水準なのですが、
以前言っていたとおり、クエリビルダを使うともっと簡潔にかけます。
こんな感じです。

```
$query = MProduct::query();
if (isset($searchWord)) {
  $query->where('product_name', 'like', '%'.$searchWord.'%');
}
if (isset($categoryId)) {
  $query->where('category_id', $categoryId);
}
$products = $query->orderBy('category_id', 'asc')->paginate(15);
```

クエリビルダは処理を連続して記述できるので、
条件分岐の中で同じ処理を書くことを極限までなくすことができます！

なかじさんが書かれている、下記の辺りが、１回の記述で済むということですね。
　※現状条件分岐の中で共通して書かれている処理↓
```
$products = MProduct::with('mCategory')
               ->where('product_name', 'like', '%' . $search_text . '%')
　　　　　->orderBy('category_id', 'asc')
                ->orderBy('product_name', 'asc')
                ->paginate(3);
```

今の記述でも十分素晴らしく正解なので、
今回は書き換えなくてもOKですが、今後の参考までに
覚えてみてください✨

2021-02-03 05:41 UTC, SekiYukihiro approved these changes
確認しました！

orderByRawや、
collationまで使われていて、
テクニカルかつヒラガナ検索への気遣いなども素晴らしいと思います😊

マージしましたので、ご確認下さい✨

2021-02-03 05:42 UTC, merged