Feature/daichi/search
quest-academia/qa-laravel-ec-training pull request #22
Opened 2021-02-01 12:22 UTC by daichi1123

検索機能完了いたしました！

お手数ですが確認よろしくお願いいたします！

2021-02-01 14:33 UTC, ykykmumu reviewed
動作確認取れ次第もう一度みますが、とりあえずseederだけ流せるようにしていただけますか？
もしdaichiさんの環境で問題なさそうだったら僕の環境のせいかもなので、教えてください！

2021-02-01 14:33 UTC, ykykmumu commented on database/seeds/ProductsTableSeeder.php
> +        DB::table('m_products')->insert([
特に直さなくてもいいですが、要素をカンマ区切りでかけばDB::table('m_products')->insertを一回書くだけでいけます。

2021-02-01 14:33 UTC, ykykmumu commented on database/seeds/DatabaseSeeder.php
>              ProductsStatusTableSeeder::class,
こちらだいちさんの環境で問題なく流せましたでしょうか？
僕の環境だと  ReflectionException  : Class ProductsStatusTableSeeder does not existのエラーが出ます。

2021-02-01 14:53 UTC, daichi1123 commented on database/seeds/ProductsTableSeeder.php
> +        DB::table('m_products')->insert([
一応、私が作成したm_shipments_statusesのシーダファイルはムランパさんが言われた通りに書いております！
元々作っていただいていたシーダファイルでしたので、そこはそのファイルに記述してあったものに従って記述いたしました。

2021-02-01 14:55 UTC, daichi1123 commented on database/seeds/DatabaseSeeder.php
>              ProductsStatusTableSeeder::class,
今回は、私の環境では、問題なく流すことができました！
前回同じ変更をした際は、エラーが出ていたのですが、今は問題なく流れている状態です！

2021-02-02 14:22 UTC, ykykmumu commented on database/seeds/ProductsTableSeeder.php
> +        DB::table('m_products')->insert([
なるほど、了解です！

2021-02-02 14:53 UTC, ykykmumu reviewed
seederは僕の環境の問題でした、失礼しました！
動作確認しましたが、僕の確認した範囲では問題なく完璧に挙動していました！
コードも特に指摘するところはありません。
とても素晴らしいと思いました！

2021-02-02 14:53 UTC, ykykmumu commented on database/seeds/DatabaseSeeder.php
>              ProductsStatusTableSeeder::class,
こちら僕の環境の問題でした

2021-02-02 21:31 UTC, SekiYukihiro requested changes
確認しました！

クエリビルダをマスターされていて、とてもすごいと思います😊

いくつか細かい点で修正いただきたいことをコメントしましたので
ご確認の上、修正お願い致します！

2021-02-02 21:31 UTC, SekiYukihiro commented on app/Category.php
> +    public static function joinName()
処理を関数化されていて、とても良いと思います😊

ただ、joinNameだと名前が分かりにくいので、関数名を直しましょう。

「カテゴリー名とIDを抽出している」ことがわかる関数名だと良いかもですね。

2021-02-02 21:31 UTC, SekiYukihiro commented on app/Http/Controllers/ProductsController.php
> +        $categoryId = $request->input('カテゴリID');
間違いではないのですが、

$request->input('商品名');

この商品名、カテゴリIDを日本語にするということはあまりないので、
英語の方がいいかなと思います！

$request->input('product_name');

2021-02-02 21:31 UTC, SekiYukihiro commented on app/Http/Controllers/ProductsController.php
> +        $products = $query->orderBy('category_id', 'asc')->paginate(15);
きちんとクエリビルダをつかわれていて、素晴らしいですね。

2021-02-02 21:31 UTC, SekiYukihiro commented on resources/views/products/search.blade.php
> +                <input type="text" class="form-control" name="商品名">
ここのnameも英語にしましょう！

2021-02-02 21:31 UTC, SekiYukihiro commented on resources/views/products/search.blade.php
> +                <select class="ml-2" style="width:50%; text-align-last:center;" name="カテゴリID">
ここのnameも英語にしましょう！

2021-02-03 02:46 UTC, daichi1123 commented on app/Http/Controllers/ProductsController.php
> +        $categoryId = $request->input('カテゴリID');
商品名→product_name
カテゴリ→category_id
に修正いたしました！

2021-02-03 02:47 UTC, daichi1123 commented on resources/views/products/search.blade.php
> +                <select class="ml-2" style="width:50%; text-align-last:center;" name="カテゴリID">
こちらもコントローラと同じ様に
商品名→product_name
カテゴリ→category_id
修正いたしました！

2021-02-03 06:17 UTC, daichi1123 commented on resources/views/products/search.blade.php
> +                <input type="text" class="form-control" name="商品名">
こちらもコントローラと同じ様に
商品名→product_name
に修正いたしました！

2021-02-03 06:17 UTC, daichi1123 commented on resources/views/products/search.blade.php
> +                <select class="ml-2" style="width:50%; text-align-last:center;" name="カテゴリID">
こちらもコントローラと同じ様に
カテゴリ→category_id
に修正いたしました！

2021-02-03 06:18 UTC, daichi1123 commented on app/Category.php
> +    public static function joinName()
関数名を
joinName→pickUpColumn
に変更いたしました！

2021-02-03 08:25 UTC, SekiYukihiro approved these changes
OKです！
確認しました😊

メソッドの命名もいいですね。

先程のレビューで書いてませんでしたが、
先週zoomで見させて頂いた時と比べて
格段に良くなりましたね❗️

マージしましたので、次はHEROKUにデプロイをやってみましょう✨

可能であれば、ご自分でTrelloのカードを作って
Heroku へのデプロイのタスク期限を決めてみてください❗️

2021-02-03 08:26 UTC, merged