Feature/daichi/detail a product
quest-academia/qa-laravel-ec-training pull request #23
Opened 2021-02-06 08:33 UTC by daichi1123

商品詳細画面が完成いたしました！
確認よろしくお願いいたします！

＊カートページ遷移のためのボタンに関しましては、カート機能を作成の際に実装していく様にいたします！

2021-02-06 15:09 UTC, ykykmumu reviewed
動作に関しては問題ありませんでした！
コードも全体的にできていると思いますが、
いくつかコメントさせていただきましたので、ご確認ください！

2021-02-07 07:53 UTC, daichi1123 commented on resources/views/products/search.blade.php
> +            <td name="name" value="商品詳細">
修正完了いたしました！

2021-02-07 07:53 UTC, daichi1123 commented on resources/views/products/detail_a_product.blade.php
> +                <input type="submit" class="btn btn-primary ml-4" value="カートへ">
修正完了いたしました！

2021-02-07 07:55 UTC, daichi1123 commented on app/Http/Controllers/ProductsController.php
> +        $categories = Category::pickUpColumn();
ここは私の解釈が間違っておりました！

$query = Product::query();
$categories = Category::pickUpColumn();

上記の文は、削除して実装していきます！

2021-02-07 09:12 UTC, daichi1123 commented on resources/views/products/detail_a_product.blade.php
> +            <form action="" method="post">
修正完了いたしました！

2021-02-07 09:14 UTC, daichi1123 commented on resources/views/products/search.blade.php
> +            <td name="name" value="商品詳細">
修正完了いたしました！

商品詳細→detailAProduct

2021-02-07 09:15 UTC, daichi1123 commented on resources/views/products/detail_a_product.blade.php
> +                <input type="submit" class="btn btn-primary ml-4" value="カートへ">
inputタグをbuttonタグに変更し解決いたしました！

2021-02-07 09:16 UTC, daichi1123 commented on resources/views/products/detail_a_product.blade.php
> +        <div class="row">
どこを直せばいいかが少し話からなったので一応直してみましたのでお手数ですが、確認よろしくお願いいたします！

2021-02-07 13:52 UTC, ykykmumu commented on resources/views/products/detail_a_product.blade.php
> +        <div class="row">
ごめんなさい、これは元からこういうモックアップだったんですね笑
勝手に崩れてると思い込んで指摘してしまいました、失礼しました！

2021-02-07 13:52 UTC, ykykmumu commented on app/Http/Controllers/ProductsController.php
> +        $categories = Category::pickUpColumn();
オッケーです

2021-02-07 13:53 UTC, ykykmumu commented on resources/views/products/detail_a_product.blade.php
> +                <input type="submit" class="btn btn-primary ml-4" value="カートへ">
確認しました！

2021-02-07 13:54 UTC, ykykmumu commented on resources/views/products/detail_a_product.blade.php
> +            <form action="" method="post">
確認しました！

2021-02-07 13:54 UTC, ykykmumu commented on resources/views/products/search.blade.php
> +            <td name="name" value="商品詳細">
おけーです！

2021-02-07 21:21 UTC, quest-academia requested changes
確認しました！

綺麗に作っていただいていると思いますので
ほぼ完璧です😊

細かい部分だけ指摘しましたので、
そちらのご確認をお願い致します❗️

2021-02-07 21:21 UTC, quest-academia commented on app/Http/Controllers/ProductsController.php
> +    public function showDetail(Request $request, $id)
第一引数のRequest $requestですが、
使っていないのであれば、不要ではないでしょうか？

2021-02-07 21:21 UTC, quest-academia approved these changes

2021-02-08 01:09 UTC, daichi1123 commented on app/Http/Controllers/ProductsController.php
> +    public function showDetail(Request $request, $id)
修正完了いたしました！

2021-02-08 03:23 UTC, SekiYukihiro approved these changes
OKです！
問題ないのでマージしました😊

引き続き宜しくお願い致します！

2021-02-08 03:24 UTC, merged