[daichi] add:cart_function
quest-academia/qa-laravel-ec-training pull request #28
Opened 2021-02-16 08:22 UTC by daichi1123

カート機能の実装が完了いたしました！

お手数ですが、確認よろしくお願いいたします！

2021-02-17 14:57 UTC, daichi1123 commented
最近いつものコマンドでコミットしようとすると全てのものをコミットしないとうまく動作しなくなってしまっており全てのファイルをコミットしてしまっている状態です💦
恐らく、ステージングする際に何か間違いがあるとおもわれます

今回の修正箇所は、
コミットメッセージがchange:CartControllerfileの中のCartControllerのファイルのみの修正ですよろしくお願いいたします！

2021-02-19 18:00 UTC, ykykmumu reviewed
かなり難しかったと思いますが、いかがでしたでしょうか。
コントローラのところは本当に難しかったと思います。。。
もうちょっと効率的な書き方がありそうなのですが、ちょっと思いつきませんでした、すいません笑
数点細かいところでコメントしておいたので確認お願いします！

2021-02-20 18:08 UTC, daichi1123 commented on resources/views/products/detail_a_product.blade.php
>                      <!-- <label class="control-label">購入個数</label> -->
こちらは、
`CartController.php`
`15`行目←<input type="hidden" name="products_id" value="{{ $product->id }}">
`40`行目←<input type="hidden" name="users_id" value="{{ $user->id }}">
などで必要と思われますので、今はおかせていただきます。

2021-02-20 18:08 UTC, daichi1123 commented on resources/views/info/cart.blade.php
> +    <div class="col-sm-11">
修正完了いたしました！

2021-02-20 18:16 UTC, daichi1123 commented on app/Http/Controllers/CartController.php
> +    public function addToCart(Request $request)
はい！
ありがとうございます！！
以前より理解度は、深まったのですが、引き続き学んでいきたいと思います！！

2021-02-20 18:16 UTC, daichi1123 commented on app/Http/Controllers/ProductsController.php
> +            'categoryId' => $categoryId,
削除しておきました！

2021-02-21 04:40 UTC, ykykmumu approved these changes

2021-02-21 22:36 UTC, quest-academia requested changes
確認しました！
難易度最高の課題を、よくここまで進められたと思います😊

少しの修正のお願いがあります。

あと、他の方のコードを真似するだけでも十分勉強になるのですが、
今回は、理解度チェックの質問をGitHub上で投げさせて頂きました。

GitHubにコメントする形でご回答頂ければと思います😊

2021-02-21 22:36 UTC, quest-academia commented on app/Http/Controllers/CartController.php
> +                        $data['category_name'] = $product['category']->category_name;
こちら、この書き方でも悪くはないのですが、
下記の書き方の方が、Laravelの原則に則していて、いいかなと思います！

$data['category_name'] = $product->category->category_name;

2021-02-21 22:36 UTC, quest-academia commented on app/Http/Controllers/CartController.php
> +                    if($product->id == $data['session_products_id']) {
他の部分では、 「===」という形で、
値の型の一致判定までされているので、
ここも可能であれば、
イコール２つではなく３つに統一した方が良いかなと思います！

2021-02-21 22:36 UTC, quest-academia commented on app/Http/Controllers/CartController.php
> +                    $request->session()->put('cartData.' . $index . '.session_quantity', $quantity);
全体的に、良く書けていると思います！

ただ、ここの部分が結構ややこしいので、
ここで理解度チェックテストをさせて下さい。

この２９行目、

`$request->session()->put('cartData.' . $index . '.session_quantity', $quantity);`

この処理が何をやっているかを文章で説明していただくことは可能でしょうか？

`「◯◯という配列のうち、××の中の△△を●●とする処理です」`

くらいの簡単な記述で大丈夫です。

2021-02-22 07:08 UTC, daichi1123 commented on app/Http/Controllers/CartController.php
> +<?php
了承いたしました！

2021-02-22 07:12 UTC, daichi1123 commented on app/Http/Controllers/CartController.php
> +                        $data['category_name'] = $product['category']->category_name;
修正完了いたしました！

2021-02-22 07:13 UTC, daichi1123 commented on app/Http/Controllers/CartController.php
> +                    if($product->id == $data['session_products_id']) {
確かに統一した方が見栄えも良さそうですね！！
修正いたします！

2021-02-22 07:14 UTC, daichi1123 commented on app/Http/Controllers/CartController.php
> +                    if($product->id == $data['session_products_id']) {
修正いたしました！

2021-02-22 15:10 UTC, daichi1123 commented on app/Http/Controllers/CartController.php
> +                    $request->session()->put('cartData.' . $index . '.session_quantity', $quantity);
「cartDataという配列の$indexに入り、session_quantityを$quantityで新たな値を算出しputしている」
こちらでお願いいたします！

2021-02-22 15:12 UTC, daichi1123 commented on app/Http/Controllers/CartController.php
> +<?php
こちらは後ほど追加を入れていきます！

2021-02-22 22:26 UTC, quest-academia approved these changes
OKです！

書いていた「このコードで何を示しているか」のコメントアウトも、
またお時間がある時に追記していって下さいね！

宜しくお願い致します😊

2021-02-22 22:26 UTC, quest-academia commented on app/Http/Controllers/CartController.php
> +                    $request->session()->put('cartData.' . $index . '.session_quantity', $quantity);
ありがとうございます！

ほぼ合っていますが、
「$indexに入り」「putしている」辺りは表現として分かりづらいので
もう少し日本語として噛み砕いた表現で表した方がDAICHIさんのご理解も深まると思います。

●回答例
　cartDataという多次元配列のうち、
　$index番目（indexが0なら、配列の0番目）のsession_quantity（商品数量）というキーを持つ値を、$quantityという変数で置き換える処理です。

ポイントはcartDataが多次元配列になっていて、その中の$index番目の、更に奥に存在する値を書き換えるように指定しているところです。　
この辺り、難しいですが、PHPに限らず、どの言語の実務でもよく使う部分ですので
もしご理解が浅ければ、ご質問ください😊

2021-02-22 22:26 UTC, merged

2021-02-23 16:36 UTC, daichi1123 commented
ありがとうございます！
はい、細部に渡るまでのチェックありがとうございます！