add:top画面no
quest-academia/qa-laravel-ec-training pull request #3
Opened 2020-12-22 10:29 UTC by fuku-git

##

2020-12-23 00:38 UTC, KyoheiYamamoto commented on resources/views/commons/header.blade.php
> +        <li class="list-inline-item"><a class="nav-link" href="#">新規登録</a></li>
文字の色が青色になっているのでhttps://docs.google.com/spreadsheets/d/1HitH3A_PX9ePJN2PhGnGB9yV-sv_FfcF/edit#gid=116395363
確認したらわかりますがここの文字は黒色にしましょう！

2020-12-23 00:41 UTC, KyoheiYamamoto commented on resources/views/welcome.blade.php
> +            <div class="colcol-xs-12 col-md-6 text-center pb-5">
こちらタイポミスですかね？？

2020-12-23 00:47 UTC, fuku-git commented on resources/views/commons/header.blade.php
> +        <li class="list-inline-item"><a class="nav-link" href="#">新規登録</a></li>
了解しました！修正します！

2020-12-23 00:49 UTC, fuku-git commented on resources/views/welcome.blade.php
> +            <div class="colcol-xs-12 col-md-6 text-center pb-5">
colcol-xs-12 になってますね💦 修正します！

2020-12-23 00:51 UTC, KyoheiYamamoto commented on resources/views/welcome.blade.php
> +                <button type="button" class="btn btn-primary btn-md">ログイン</button>
こちら下記の画像みたらわかると思いますが、画面サイズが750px以下になると
文字とボタンの位置がずれていますので修正をお願いします

![image](https://user-images.githubusercontent.com/57794595/102946273-81cf5880-4503-11eb-8398-4c496b1ee60b.png)

2020-12-23 00:58 UTC, KyoheiYamamoto commented on resources/views/commons/header.blade.php
> +    <a class="navbar-brand text-dark" style="font-size:x-large;" href="">
なるべくstyleは使わずにCSSに任せちゃいましょう！
そちらの方が可読性が向上しますよ〜

2020-12-23 00:59 UTC, fuku-git commented on resources/views/welcome.blade.php
> +                <button type="button" class="btn btn-primary btn-md">ログイン</button>
かしこまりました！修正します！

2020-12-23 01:00 UTC, KyoheiYamamoto commented on resources/views/layouts/app.blade.php
> +        <meta http-equiv="X-UA-Compatible" content="ie=edge">
ここもmetaタグが3つも並んでいるのでまとめきっちゃいましょう！

2020-12-23 01:01 UTC, fuku-git commented on resources/views/commons/header.blade.php
> +    <a class="navbar-brand text-dark" style="font-size:x-large;" href="">
承知しました！修正します！
ちなみにCSSは public/css にファイルを配置してCSSを効くようにしたらいいでしょうか？

2020-12-23 01:02 UTC, KyoheiYamamoto requested changes
コンフリクトの解消と
細かいですが、いくつか修正点があるので確認のほどよろしくお願いします。
基本的にはReactQuest受講されているのでスムーズにできているので良いと思います！

2020-12-23 01:07 UTC, fuku-git commented on resources/views/layouts/app.blade.php
> +        <meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta charset="UTF-8" name="viewport" 
            content="width=device-width, initial-scale=1.0"
            http-equiv="X-UA-Compatible" content="ie=edge"           
>

metaタグはこのようにまとめて問題ないということでしょうか？

2020-12-23 01:11 UTC, KyoheiYamamoto commented on resources/views/layouts/app.blade.php
> +        <meta http-equiv="X-UA-Compatible" content="ie=edge">
おっしゃる通りですね！適宜インデントまでしたら完璧です！！

2020-12-23 01:12 UTC, KyoheiYamamoto commented on resources/views/commons/header.blade.php
> +    <a class="navbar-brand text-dark" style="font-size:x-large;" href="">
僕はそのようにした方が良いかなと思っています。それかBootrapでクラスを探して代用するかどちらかですね〜

2020-12-23 01:19 UTC, fuku-git commented on resources/views/commons/header.blade.php
> +    <a class="navbar-brand text-dark" style="font-size:x-large;" href="">
承知しました！
ReactQuestで習ったことを活かしたいのでCSSで修正します！

2020-12-23 01:20 UTC, fuku-git commented on resources/views/layouts/app.blade.php
> +        <meta http-equiv="X-UA-Compatible" content="ie=edge">
かしこまりました！修正します！
metaタグはまとめていいということを初めて知りました😅
ありがとうございます！

2020-12-23 23:39 UTC, KyoheiYamamoto requested changes
コンフリクトの修正ありがとうございます！
私から一部指摘がありますのでそちらを修正をよろしくお願いします。

2020-12-23 23:40 UTC, KyoheiYamamoto commented on public/css/style.css
> +}
CSSのファイル名はなるべくstyle.cssではなくheaderのCSSならheader.cssなどに変えた方が可読性が向上しやすく、修正も少しだけ楽になります

2020-12-23 23:43 UTC, KyoheiYamamoto commented on resources/views/layouts/app.blade.php
> +        <link rel="stylesheet" href="{{ asset('css/style.css') }}">
ここの修正も変わってくると思います

2020-12-24 00:18 UTC, SekiYukihiro approved these changes
確認しました。
綺麗に書いて頂いていると思います！

僕の方からは特に指摘はありませんので
きょうへいさんのご指摘の修正が終わりましたらそのまま進めていただければと思います！

2020-12-24 00:19 UTC, KyoheiYamamoto commented on resources/views/commons/footer.blade.php
> +        <div class="navbar-brand-02 text-dark">
CSSにスタイルを反映しても良いですね、
こちらは画面定義書みたらわかると思いますが位置を少しだけ下に持っていきましょうか！
あと、divタグ使ってCSSで文字の調整をされていますが、pタグとか使ってやる方が
可読性が向上し無駄にCSSを書かなくてよくなるかなと個人的には思います

2020-12-24 00:42 UTC, KyoheiYamamoto reviewed
修正できているのを確認しました。
LGTMです！
ここまでお疲れ様でした

2020-12-24 00:42 UTC, KyoheiYamamoto approved these changes

2020-12-24 00:48 UTC, merged

2020-12-24 00:49 UTC, KyoheiYamamoto commented on resources/views/layouts/app.blade.php
> +        <meta http-equiv="X-UA-Compatible" content="ie=edge">
これ僕もしおたさんに指摘されて言われたことなのですよ