migration_daichi
quest-academia/qa-laravel-ec-training pull request #4
Opened 2020-12-23 18:14 UTC by daichi1123

migration完了いたしました！
よろしくお願いいたします。

2020-12-25 07:09 UTC, daichi1123 commented
修正完了いたしました！
修正内容：
プライマリーキーの部分を`id`に変更
プライマリーキー変更に伴ったseederファイルの変更
よろしくお願いいたします！

2020-12-26 04:08 UTC, ykykmumu reviewed
テスト

2020-12-26 05:30 UTC, ykykmumu reviewed
全体的にコーディング規約に沿った記述（カンマ後の空白など）でいいと思います！

一点だけ申し訳ないのですが、
今PCが固まって動かないので、動作確認だけしていません。

コードのみ見させて頂いて
数点コメントしておきましたのでご確認ください。
ご不明点ありましたら聞いてください。

2020-12-26 05:30 UTC, ykykmumu commented on database/migrations/2020_12_22_104435_create_t_orders_details_table.php
> +            $table->integer('order_quanity');
quantityのスペルが違います。

2020-12-26 05:30 UTC, ykykmumu commented on database/seeds/ShipmentsStatusesTableSeeder.php
> +                'shipment_status_name' => '発送中',
status_nameはstatus_idと紐付きますよね。
上でidを1,2,3としてデータを流すので有ればここもそれに対応して3種類のstatus_nameを入れた方がいいかなと思いました。なので発送中だけじゃなくてほかのステータスを入れてみてもいいかもです！

2020-12-26 22:54 UTC, quest-academia requested changes
お疲れ様でした！

苦戦されたと思いますが、
コーディング規約については、ムランパさんが指摘の部分以外
十分配慮して書いていただいていると思います！

僕からも少しだけ、
修正頂きたい点がありますので
詳しくは各コメントをご覧いただければと思います。

宜しくお願い致します😊

2020-12-26 22:54 UTC, quest-academia commented on database/migrations/2020_12_22_104228_create_t_orders_table.php
> +            // ->onDelete('cascade');
m_usersテーブルは、現時点でフクさんの変更が既に取り込まれているはずなので、
フクさんのシーダーが先に実行されるように実行の順番さえ気をつければ
ここはコメントアウトではなく、普通の外部キー制約として書けるはずです😊

宜しくお願い致します❗️

2020-12-26 22:54 UTC, quest-academia commented on database/seeds/DatabaseSeeder.php
>              SalesStatusesTableSeeder::class,
上記で書いている実行の順序はここで変わってくると思うので
この順番を入れ替える必要があるかと思います！

2020-12-27 03:01 UTC, daichi1123 commented
修正完了いたしました！

2020-12-28 01:08 UTC, quest-academia approved these changes
OKです！

あとはムランパさんに動作確認をしていただきたいと思います😊

2020-12-29 09:23 UTC, merged