ログイン機能を実装[フク]
quest-academia/qa-laravel-ec-training pull request #5
Opened 2020-12-28 05:19 UTC by fuku-git

## 実装一覧

- ログイン前、ログイン後の画面を追加
- ログイン後のheaderリンクを追加
- 各ページリンクへの遷移を追加

新規登録画面も追加しておりますがこちらはともさんに引き継ぐ予定です。
実務で引継ぎなどはどうされているのか教えていただけると嬉しいです！
レビューよろしくお願いいたします！

2020-12-28 06:55 UTC, KyoheiYamamoto commented
僕から指摘事項がいくつかございますのでそちらをご確認くださいませ

2020-12-28 06:57 UTC, KyoheiYamamoto commented on app/Http/Controllers/Auth/LoginController.php
> +    protected $redirectTo = '/login_after';
あまり「login_after」とは使わない方が賢明ですね、
ログイン後は例えば「top」とかにした方が無難かなと個人的には思います。

2020-12-28 07:03 UTC, KyoheiYamamoto commented on resources/views/auth/register.blade.php
> +                        {!! Form::label('municipality', '市町村区') !!}
こちら細かいですが、市区町村に修正をお願いします

2020-12-28 07:11 UTC, KyoheiYamamoto commented on app/Http/Controllers/LoginAfterController.php
> +        return view('login_after');
こちらも同じようになるかと思いますよ

2020-12-28 07:15 UTC, KyoheiYamamoto commented on database/seeds/UsersTableSeeder.php
> +            'password' => bcrypt('test1'),
こちらは半角英数字になっているにはpasswordが入るから半角英数字に対応できるように変更してはってことですかね？？

2020-12-28 07:43 UTC, KyoheiYamamoto commented on resources/views/welcome.blade.php
> +                        </button>
せっかくなのでログインもLaravel collectiveを使いましょうか

2020-12-28 07:46 UTC, KyoheiYamamoto commented on routes/web.php
> +});
ファイルの最後に1行の改行をお願いしますPSR-2 記法

2020-12-28 07:52 UTC, KyoheiYamamoto commented on app/Http/Controllers/LoginAfterController.php
> +}
ファイルの最後に1行の改行をお願いしますPSR-2 記法

2020-12-28 20:30 UTC, quest-academia commented on app/Http/Controllers/Auth/LoginController.php
> +    protected $redirectTo = '/login_after';
今回であれば、
/topでもいいですし、
/だけの方が良いのかなと思いますね😊

2020-12-28 20:48 UTC, quest-academia requested changes
きょうへいさんのコメントに追記する形で
引継ぎのやり方など、僕の方もコメントを書きました！

また、
app/Http/Controllers/Auth/LoginController.php 
に記述いただいている通り、
redirectToを変えることでログイン後の画面遷移を決定できるのですが
併せて、
RedirectIfAuthenticated.phpというファイルがMiddlewareフォルダ内に存在しますので
そちらの記述も
/homeから、画面遷移後のアドレスに変更してみてください。

そうすると、ログイン済みユーザがログイン画面に行こうとすると
強制的にログイン後画面にリダイレクトされる仕様になります。

2020-12-28 20:48 UTC, quest-academia commented on resources/views/auth/register.blade.php
> +@endsection
業務で引継ぎを行う場合は、
コメントアウトで例えば下記のように書きます。

// TODO
// 新規登録のバリデーションと新規登録機能未実装
// 新規登録フォームのみ作成しましたので、実装をお願いします

これをこのファイルでも良いですし、
新規登録のバリデーションなどが実装されるファイルに記述しておきましょう✨

2020-12-29 03:08 UTC, fuku-git commented on app/Http/Controllers/Auth/LoginController.php
> +    protected $redirectTo = '/login_after';
承知しました！変更します。

2020-12-29 03:08 UTC, fuku-git commented on resources/views/auth/register.blade.php
> +                        {!! Form::label('municipality', '市町村区') !!}
承知しました！変更します。

2020-12-29 03:08 UTC, fuku-git commented on app/Http/Controllers/LoginAfterController.php
> +        return view('login_after');
承知しました！変更します。

2020-12-29 03:09 UTC, fuku-git commented on database/seeds/UsersTableSeeder.php
> +            'password' => bcrypt('test1'),
はい、おっしゃる通りです。パスワードを打つときに英数字意外だと
入力できなかったので変更しました！

2020-12-29 03:10 UTC, fuku-git commented on resources/views/welcome.blade.php
> +                        </button>
承知しました！変更します。

2020-12-29 03:10 UTC, fuku-git commented on routes/web.php
> +});
承知しました！気をつけます。

2020-12-29 03:11 UTC, fuku-git commented on app/Http/Controllers/LoginAfterController.php
> +}
承知しました！気をつけます。

2020-12-29 03:13 UTC, fuku-git commented on resources/views/auth/register.blade.php
> +@endsection
承知しました！コメントアウトで対応するのですね✨
教えていただきありがとうございます！

2021-01-03 13:38 UTC, quest-academia approved these changes
フクさん、ご変更ありがとうございます！

僕の方はこの内容でOKですので、
きょへさんがOKであれば、マージお願い致します😊

2021-01-03 13:54 UTC, KyoheiYamamoto commented
僕も確認しました。
特に指摘事項がないのでこちらをmergeしておきます！
お疲れ様でした

2021-01-03 13:54 UTC, merged