DBユーザー周り実装。#54
quest-academia/qa-laravel-ec-training pull request #58
Opened 2021-05-24 12:24 UTC by Hikaru-Giannis

お疲れ様です。

やったこと
- ユーザ周りのマイグレーションファイルを作成。
- ユーザ周りのシーダーを作成。

考慮して欲しいこと
- シーダーではユーザ種別毎に3つずつサンプルデータを登録するようにしました。
- ユーザ種別に関しては現状はせきさんのアドバイス通りの3つを用意し、仕様に合わせて適宜変更しようと考えています。

確認のほどよろしくお願いします。

2021-05-26 03:49 UTC, hsg0830 reviewed
@Hikaru-Giannis 

お疲れ様です！
遅くなって本当にすみません！

さすがだなぁと思いながら拝見しました。

いくつか感じたことをコメントに残しておきましたので、
ご参考程度にご覧いただければと思います！

正直、seederの書き方など好みの問題になっちゃう面もあるかと思いますが、
どのみちダミーデータなので、
僕だったらもう少しズルして楽して短く書いちゃいそうだな、と思いました。

2021-05-26 03:49 UTC, hsg0830 commented on app/Providers/AppServiceProvider.php
>      }
こちら既にご存知かもしれないですが、
念のためにメモを残しておきますね。

このコードは、MySQLのバージョンが5.7.7より古い時にだけ必要になってきます。
https://readouble.com/laravel/6.x/ja/migrations.html#creating-indexes

現状のDocker見ると、5.7なので、書いてくださって正解ですね^^
https://github.com/yuya-ishikawa-qa/docker-laravel/blob/master/docker-compose.yml

2021-05-26 03:49 UTC, hsg0830 commented on database/migrations/2021_05_23_081555_create_m_user_classifications_table.php
> +            $table->string('user_classification_name', 32);
大した問題ではないですが、ここの順序でカラムの並びが決まってしまいますので、メインの内容にあたる`user_classification_name`は、並びとして、`created_at`などより前にあった方がいいんじゃないかな、と個人的には思います^^;

2021-05-26 03:49 UTC, hsg0830 commented on database/migrations/2021_05_23_081556_create_m_users_table.php
> +            $table->foreign('user_classification_id')->references('id')->on('m_user_classifications')->onDelete('cascade');
個人的な意見なので、ご参考までに…。

・電話番号までユニークにするのはいいかどうか…。電話番号ででもログインできるようにするとかではない限り不要なのでは？　実際のECとかの運用考えても、一人がアカウントは2つあるけど、電話は1台しか持ってないというようなこともありますし… （僕自身そうで。。。^^;)

・`delete_flag`の内容だけ見てると、`boolean`とかでもいいのかな…と。

・最後の`onDelete`ですけど、今の状態だと、あるユーザー種別が削除されたら、それに紐づくユーザー全員削除になるんですよね…？ソフトデリートとかの設定すると、救済できるのかもですが…

2021-05-26 03:49 UTC, hsg0830 commented on database/seeds/UsersTableSeeder.php
> +        $admin = UserClassification::where('user_classification_name', '管理者')->first();
既に`UserClassification`のSeedingは終わってるので、`id'を用いるだけでいいのでは？

2021-05-26 03:49 UTC, hsg0830 commented on database/seeds/UsersTableSeeder.php
> +                    'company_name' => null,
・user_classification_idのところは上に書いた通りです。

・あと、company_nameのようにマイグレーションで`nullable()`にしてるカラムは、不要な場合はseederに含めなくても大丈夫かと思います。

2021-05-26 12:26 UTC, Hikaru-Giannis commented on database/migrations/2021_05_23_081556_create_m_users_table.php
> +            $table->foreign('user_classification_id')->references('id')->on('m_user_classifications')->onDelete('cascade');
レビューしていただきありがとうございます！

> 電話番号までユニークにするのはいいかどうか

自分も電話番号に関してはユニークでなくてもいい気がするので、制約を外すように修正させていただきます！

> delete_flagの内容だけ見てると、booleanとかでもいいのかな

一応いただいたER図では`char(1)`だったのでせきさんのレビュー等を参考に検討してみようと思います。別の方法として現段階では認識しておきます。

>  最後のonDeleteですけど、今の状態だと、あるユーザー種別が削除されたら、それに紐づくユーザー全員削除になるんですよね…？ソフトデリートとかの設定すると、救済できるのかもですが…

上記についてお聞きしたことがありました。共有していただいた`deleteフラグ`は`char(1)`でしたので、softDeletesを利用すると`timestamp`になることから避けた方が良いのかなと考えていたのですが、あくまでこれらは実装内容の提案であって他の方法でも内容次第では実装して良いという認識でよろしいでしょうか？

立て続けで申し訳ございませんが、ユーザ種別が削除される場合は物理削除にあたり、その際に紐づいているユーザーは論理削除する必要があるという認識でよろしいでしょうか？
どちらとも論理削除であればModelのbootメソッドをオーバーライドすれば可能なのではと考えられたのですが、
ユーザ種別の物理削除をトリガーに紐づいているユーザを論理削除する方法がわかりませんでした...。
何か方法があればアドバイスをしていただきたいです。

よろしくお願いします。

2021-05-26 12:33 UTC, Hikaru-Giannis commented on database/seeds/UsersTableSeeder.php
> +        $admin = UserClassification::where('user_classification_name', '管理者')->first();
レビューしていただきありがとうございます！

> `id'を用いるだけでいいのでは？

上記に関しては自分もユーザー種別に該当する`id`を用いるだけで良いと考えていたのですが、
今後のECサイトの仕様において、変動しやすい箇所であるのかなと考えられたのでわざわざ`id`を確認しなくても修正できるように実装した感じでした。極端に種別が増えたり、内容が変わることはないと思われますが...。

あるいは`id`だけをselectした方が良いという認識でしょうか？
よろしくお願いします。

2021-05-26 12:34 UTC, Hikaru-Giannis commented on app/Providers/AppServiceProvider.php
>      }
ありがとうございます！
参考にさせていただきます。

2021-05-26 12:34 UTC, Hikaru-Giannis commented on database/migrations/2021_05_23_081555_create_m_user_classifications_table.php
> +            $table->string('user_classification_name', 32);
ありがとうございます！
確かに他と並びを揃えた方がよいと思うので、レビューを参考に修正させて頂きます。

2021-05-27 04:00 UTC, hsg0830 commented on database/migrations/2021_05_23_081556_create_m_users_table.php
> +            $table->foreign('user_classification_id')->references('id')->on('m_user_classifications')->onDelete('cascade');
> 一応いただいたER図ではchar(1)だったのでせきさんのレビュー等を参考に検討してみようと思います。別の方法として現段階では認識しておきます。

こちら、確かにそうですね！
ER図、確認不足ですみません！
delete_flagという名前からして、
ソフトデリートされたユーザーなのかどうかを入れておくカラムなのかな？と思ったので、
それなら0/1のtrue/falseでいいのかな、と思っただけなので、
気になさらないでください！

仮に、ソフトデリートなら、おっしゃる通り、
$table->softDeletes();で、`deleated_at`が追加されるようにしなきゃですし、
おそらく僕の見当違いですね💦

> あくまでこれらは実装内容の提案であって他の方法でも内容次第では実装して良いという認識でよろしいでしょうか？

すみません！この点は僕も把握しきれておらず、せきさんの回答をお待ちいただければと思います！

> 立て続けで申し訳ございませんが、ユーザ種別が削除される場合は物理削除にあたり、その際に紐づいているユーザーは論理削除する必要があるという認識でよろしいでしょうか？
どちらとも論理削除であればModelのbootメソッドをオーバーライドすれば可能なのではと考えられたのですが、
ユーザ種別の物理削除をトリガーに紐づいているユーザを論理削除する方法がわかりませんでした...。
何か方法があればアドバイスをしていただきたいです。

僕は、個人的に、hasManyで抱えているのがユーザーレコードであるUserClassification自体を削除すること自体、やっていいことなのかな？仮にそうした場合、ユーザーやそれに紐づく予定のオーダー情報なども削除されるし、そもそも削除できないように、`restrict`であるべきなのでは？と思った次第です。
ここら辺もせきさんのご指導を仰ぎたいと思います。
中途半端な回答で申し訳ないです💦

2021-05-27 04:09 UTC, hsg0830 commented on database/seeds/UsersTableSeeder.php
> +        $admin = UserClassification::where('user_classification_name', '管理者')->first();
なるほどですね。
個人的には、最初になさっていたような感じで、config内での定義みたいなのがいい気がしますが、どうなんでしょうかね…。
そこにあれば、変更あった際も修正しやすいような…。
僕が予想できていないことがあったらすみません💦

2021-05-27 09:00 UTC, SekiYukihiro commented on database/migrations/2021_05_23_081556_create_m_users_table.php
> +            $table->foreign('user_classification_id')->references('id')->on('m_user_classifications')->onDelete('cascade');
> 一応いただいたER図ではchar(1)だったのでせきさんのレビュー等を参考に検討してみようと思います。別の方法として現段階では認識しておきます。

ER図ではchar(1)だったので申し訳ないのですが、HANさんがおっしゃる通り
onかoffの２択だとすればcharよりは、int型かboolean型がベストですね！
（設計書があまりよくないですね汗）


>あくまでこれらは実装内容の提案であって他の方法でも内容次第では実装して良いという認識でよろしいでしょうか？
上記の認識でOKです！

>立て続けで申し訳ございませんが、ユーザ種別が削除される場合は物理削除にあたり、その際に紐づいているユーザーは論理削除する必要があるという認識でよろしいでしょうか？
>どちらとも論理削除であればModelのbootメソッドをオーバーライドすれば可能なのではと考えられたのですが、
>ユーザ種別の物理削除をトリガーに紐づいているユーザを論理削除する方法がわかりませんでした...。
>何か方法があればアドバイスをしていただきたいです。
なので、ややこしく恐縮ですが、今回は全て論理削除でいきましょうか。
Kouさんがおっしゃる形の、Modelのbootメソッドをオーバーライドして、親テーブルのレコードも子テーブルのレコードも両方論理削除する方向でお願い致します・・・！

2021-05-27 09:21 UTC, SekiYukihiro requested changes
確認しました！
とても精度が高いと思います😊

詳細は各コメントを見ていただきたいののですが、
ややこしく恐縮ながら、今回は全て論理削除でいきましょうか。

Kouさんがおっしゃる形の、Modelのbootメソッドをオーバーライドして、親テーブルのレコードも子テーブルのレコードも両方論理削除する方向でお願い致します・・・！

設計書がわかりにくい点もあり、恐縮なのですが
お手数ながら、上記の点などを今一度修正いただければと思います。

宜しくお願い致します！

2021-05-27 09:21 UTC, SekiYukihiro commented on database/seeds/UsersTableSeeder.php
> +        $admin = UserClassification::where('user_classification_name', '管理者')->first();
結構実務よりの（レベル高めな）話になりますが、
HANさんのおっしゃるように、config内にユーザ種別を定義して、
そのユーザの種類の数だけ、for文で
UserClassificationのシーダーと、ユーザのシーダーを繰り返すようにすれば
一番綺麗かなと思いました！

2021-05-27 13:26 UTC, Hikaru-Giannis commented
お疲れ様です！

やったこと
- Laravelの論理削除機能を利用するように修正。
- シーダーにおいてユーザ種別を定数で定義するように修正。
- ユーザ種別が論理削除されたら紐づいているユーザも論理削除するように修正。

レビューを参考に修正させていただきましたので確認のほどよろしくお願いします。

2021-05-27 13:56 UTC, SekiYukihiro requested changes
とてもよくなりましたね！😊

configの書き方ですが、
今の書き方ですと、どんどん新規ファイルが増えていくので、
ファイルはcommon.phpなど共通のファイル名として、
common.php内の１つの要素として、
下記のように書くのが実務では多いかなと思いました。

```
userclassification => [
    'purchaser' =>  [
          'label' => '購入者',
          'value' => 1,
    ],
     'exhibitor' =>  [
          'label' => '出品者',
          'value' => 2,
    ],
     'admin' =>  [
          'label' => '管理者',
          'value' => 3,
    ],
],
```

2021-05-27 13:56 UTC, SekiYukihiro commented on config/consts/userclassification.php
> +    ],
とてもよくなりましたね！😊

configの書き方ですが、
今の書き方ですと、どんどん新規ファイルが増えていくので、
ファイルはcommon.phpなど共通のファイル名として、
common.php内の１つの要素として、
下記のように書くのが実務では多いかなと思いました。

userclassification => [
    'purchaser' =>  [
          'label' => '購入者',
          'value' => 1,
    ],
     'exhibitor' =>  [
          'label' => '出品者',
          'value' => 2,
    ],
     'admin' =>  [
          'label' => '管理者',
          'value' => 3,
    ],
],

2021-05-27 14:25 UTC, Hikaru-Giannis commented
おかげさまですごく勉強になります！

やったこと
- ユーザ種別定数定義箇所を修正

レビューを参考に修正させていただきましたので、確認のほどよろしくお願いします。

2021-05-27 14:57 UTC, Hikaru-Giannis commented
立て続けに何度も報告してしまい申し訳ございません...。
レビューを参考に修正しましたので確認のほどよろしくお願いします。

やったこと
- ユーザ種別の定数定義箇所を修正。

2021-05-28 00:55 UTC, SekiYukihiro approved these changes
OKです！
修正お疲れ様でした✨

問題ないと思いますので
マージさせていただきます😊

宜しくお願い致します❗️
close #54

2021-05-28 00:56 UTC, merged