m products テーブルとProductsSeederテーブル作成 [tomo]
quest-academia/qa-laravel-ec-training pull request #6
Opened 2021-01-11 05:17 UTC by suzusan555

外部キーをコメントアウトした状態でpushしています。
よろしくお願いします！

2021-01-11 07:19 UTC, KyoheiYamamoto commented on database/seeds/ProductsTableSeeder.php
> +            'product_name' => 'おかか',
この部分product_nameが2つあるのでこのままシーディングしてしまうと
おかかになってしまいますのでproduct_nameをわさびだけ残しておかかを削除しましょうか

2021-01-11 07:52 UTC, KyoheiYamamoto commented on database/migrations/2021_01_05_175954_create_m_products_table.php
> +            //       ->onDelete('cascade');
外部キー制約の部分のテーブルをちゃんと120文字以上になりそうなことを予想してインデントしているのは個人的にめっちゃ良いと思います（読みやすいからですね）

2021-01-11 07:52 UTC, KyoheiYamamoto commented
僕の方で挙動を確認しました！
問題なく動いていますね〜シーディングの記述も綺麗でした。
1つだけ指摘している部分がございますのでそちらの修正をお願いします

2021-01-11 10:56 UTC, SekiYukihiro requested changes
ご確認宜しくお願い致します❗️

2021-01-11 10:56 UTC, SekiYukihiro commented on database/migrations/2021_01_05_175954_create_m_products_table.php
> +                    // ->onDelete('cascade');
ユーザーズテーブルは既に存在するはずですので、
developを取り込めば、
ユーザーズテーブル関連の外部キー制約は現段階でコメントアウトを外せると思います。

外して実行してみてください！

2021-01-11 10:56 UTC, SekiYukihiro commented on database/migrations/2021_01_05_175954_create_m_products_table.php
> +            //       ->onDelete('cascade');
取り急ぎはこのテーブルのプッシュだけで良いのですが、
商品カテゴリテーブルやその他商品関連のテーブルもトモさんのご担当だと思っていたのですが違いましたでしょうか？

他にも担当のテーブルがあれば、
別ブランチでプッシュして下さい❗️

2021-01-14 21:59 UTC, quest-academia approved these changes
OKです！
きょへさんが問題なければ、マージしてもらいます。

宜しくお願い致します😊

2021-01-14 22:42 UTC, SekiYukihiro approved these changes

2021-01-14 23:41 UTC, KyoheiYamamoto commented
僕の方でも問題ないのでこちらはmergeします
お疲れ様でした

2021-01-14 23:41 UTC, merged