add:t_purchasesテーブルとPurchasesTableSeeder作成
quest-academia/qa-laravel-ec-training pull request #7
Opened 2021-01-11 14:38 UTC by suzusan555

よろしくお願い致します！！

2021-01-11 23:56 UTC, KyoheiYamamoto commented
こちら動作確認でしました。purchasesテーブルは正常に作成されていますが、PurchasesTableSeeder.phpのデータの中身が確認できませんでしたので、修正をよろしくお願いします。

2021-01-12 00:39 UTC, SekiYukihiro requested changes
こちら、商品テーブルのブランチが先にマージされると思いますので、
マージされたらコメントアウトを外して

テスト　→ 再度プッシュ

をお願いいたします！

2021-01-12 00:39 UTC, SekiYukihiro commented on database/migrations/2021_01_11_223630_create_t_purchases_table.php
> +            // ->onDelete('cascade');
こちら、商品テーブルのブランチが先にマージされると思いますので、
マージされたらコメントアウトを外して
テスト　→ 再度プッシュ
をお願いいたします！

2021-01-15 12:12 UTC, SekiYukihiro approved these changes
OKです！

（developでプルしてきちんとマイグレーションが動作することを確認できたら）
フクさんたちにご連絡をお願い致します❗️

2021-01-15 12:12 UTC, merged