出品者登録画面を実装。
quest-academia/qa-laravel-ec-training pull request #73
Opened 2021-06-19 14:42 UTC by Hikaru-Giannis

お疲れ様です！

やったこと
- 出品者登録画面を実装。
- 出品者登録機能を実装。
- 認証コード用のテーブルを作成。
- 出品者登録のバリデーションを実装.

仕様内容
- 認証コードは16文字にしています。
- 出品者登録画面に遷移する際に認証コードのチェックをしています。
- 出品者登録後は認証コードを物理削除して、再使用不可としています。
- 認証コードはシーダーでランダムで生成しています。

確認のほどよろしくお願いします。

2021-06-22 14:18 UTC, quest-academia requested changes
確認しました！
現状の仕様を２人で作成いただいただけでも十分素晴らしいのですが😊、
確かに、HANさんのおっしゃるような形が理想的かと思いますね・・・！

HANさんのおっしゃるように、
auth_codeテーブルに、アドレスなどのカラムも入れて、保存しておくのが
一般的な認証のやり方ですね。

ちなみに、僕が今入っているLaravelの実務現場のコードを見てみたところ
applicant(応募者)テーブルに、認証コードやメールアドレスなどの情報が入っていて、
ユーザ情報を一時保存しておいて、
正式登録となった場合、usersテーブルに新規登録されるという方式でした。

なので、このような方式をとる場合、
テーブル名もおそらくauth_codeとは変わってきて
applicantなどより相応しい名前に変えた方が良いかなと感じました✨

また、

・usersテーブルとのアドレスの重複チェック
・URLのメール送信

上記の２つの機能は、こだわられる場合は機能として作ればいいですし、
そこまでこだわられなくてもいいかなと思っています！

少し難しい実装ではありますが、
ご確認お願い致します❗️

ご不明点あればお聞き下さい！

2021-06-24 16:03 UTC, Hikaru-Giannis commented on app/Http/Controllers/UsersController.php
> +            return redirect('/');
承知しました！
アドバイスを参考に修正させていただきます。

2021-06-24 16:06 UTC, Hikaru-Giannis commented
お疲れ様です！

やったこと
- TOP画面に出品者申請画面への導線を追加。
- 出品者申請画面の実装。
- 出品者申請後にメールを送信するように実装。
- 各箇所のバリデーションを修正。

提案していただいたアドバイスを参考に実装させていただきました。
実装、考慮不足等があれば教えて頂きたいです。
確認のほどよろしくお願いします。

2021-07-01 07:14 UTC, hsg0830 approved these changes
これまでの提案を踏まえ、Mailableなども使用し、非常にしっかりと実装できていると思います！
電話番号問題などありましたが、これらはまたいつかブラッシュアップさせていくタイミングがありましたら、Kouさんのお考えのように3カラムに仕様変更するなどしての実装などにできたらいいんじゃないかな、と思います、笑
お疲れ様でした〜！

2021-07-02 09:42 UTC, quest-academia approved these changes
確認しました！

粗探ししようとしたのですが（笑）、完璧で穴が見当たらず、
とても素晴らしい実装だと思いました✨
マージ致します。

今回の実装でも、フォームリクエスト 、Mailable、独自バリデーションルールなど使われていて
共同開発期間に、Laravel実務でも使える多くのものを吸収されたと思います❗️

あと、少しレベルが高い話を、下記に参考までに書きます。

今回は（プロジェクト内での書き方を統一する意味でも）使いませんでしたが、
実務だとLaravelでも、
   app/Repositories/ApplicantRepository.php
のようなモデルを取得するためのリポジトリクラスを作って、そのクラスの中でクエリビルダを使ってデータベースの検索を掛けて、値を取得したりする場合が結構あります。
（もしかしたら、Kouさんはこういう書き方の方が得意ですか？）

なので、今後個人的にLaravelプロジェクトを立ち上げられる場合は、
モデルとは別に、上記のようなリポジトリクラスを作ってデータベースの値を取得しても良いかなと思いました。

本当にお疲れ様でした！
今後もLaravelを使って新しいことに挑戦いただければとても嬉しいです❗️

2021-07-02 09:42 UTC, quest-academia commented on app/Http/Controllers/UsersController.php
> +        }
既に消されていた場合なども、前行っていた通り考慮されていて良いですね！

2021-07-02 09:42 UTC, quest-academia commented on app/Http/Controllers/UsersController.php
> +        }
発行されたランダムなauth_codeが
万一存在していたものと一致する場合まで考慮されていて
完璧だと思います❗️

2021-07-02 09:43 UTC, merged