#89ユーザー周りのマイグレーション・シーダの作成（須賀）
quest-academia/qa-laravel-ec-training pull request #97
Opened 2021-07-19 14:58 UTC by sukapontan

やったこと(What)  
ユーザー周りのマイグレーション・シーダの作成

編集したこと(Why)  
・UserFactoryを使用してシーダーの作成
・MUserClassificationSeederの作成
・MUsersTableSeederの作成
・DatabaseSeederに実行するシーダを追記
・m_usersテーブルのマイグレーション作成
・m_user_classificationsのマイグレーション作成

レビュワーに考慮してほしいこと
 外部キー制約について理解が浅いため、間違いがあったらご指摘いただきたいです。

2021-07-19 15:06 UTC, sukapontan commented on database/migrations/2021_07_18_190716_create_m_user_classifications_table.php
> +            // $table->foreign('id')->references('user_classification_id')->on('m_users');
こちらですが、php artisan migrateを実行した際にSQLSTATE[HY000]が発生したため、原因を探りましたが以下2点が該当しなかったため、一度コメントアウトすることで実行することができました。

・テーブルの生成順序がおかしい
・制約キーのつけるカラムと、制約キーとして参照するカラムの型が一致してない

どちらも問題ないように見えるのですが、ご指摘事項あればご教示いただけますと幸いです。
※個人的な見解としては、シーダ実行前でデータが存在しないから発生しているのかなと思っています。

ご確認宜しくお願い致します。

2021-07-21 00:27 UTC, hsg0830 requested changes
お疲れ様です！
色々と研究、工夫なされて素晴らしいですね。
ひとまず思ったことや質問への回答を書かせていただきました。
※個人的には`MUser`モデルを作らなくとも、既存の`User`モデルのリンク先のテーブルだけ変更してもいいように思われますが、現状でも全然大丈夫だと思いますので、そこについてはコメントしておりません。

2021-07-21 00:27 UTC, hsg0830 commented on database/migrations/2021_07_18_190716_create_m_user_classifications_table.php
> +            // $table->foreign('id')->references('user_classification_id')->on('m_users');
こちらですが、
`m_users`に格納されるべき`user_classification_id`が、
この`m_user_classifications`のidであるべきことから、
何らかの外部キー制約がかけられるべきということになりますので、
外部キー制約に関する記述は、
こちらのテーブルではなく、`m_users`テーブルに書かれるべき内容ですね。
つまり、このテーブルが`親テーブル`で、`m_users`が`子テーブル`ってことになりますね。

また、そのため、`m-users`テーブルよりこのテーブルが先に生成されるようにする必要がありますね。

2021-07-21 00:27 UTC, hsg0830 commented on database/migrations/2021_07_18_183520_create_m_users_table.php
> +            $table->char('delete_flag', 1);
要件定義にはこうなっていますが、
`delete_flag`の本来の役割を考えると、
true/false(1/0)だけを格納するbool型でもよさそうですね。
ひとまずは現状のままでも大丈夫だとは思います。

2021-07-21 00:27 UTC, hsg0830 commented on database/factories/UserFactory.php
> +        'password' => $faker->password(),
仮に、ダミーとして登録したユーザーとしてログインしてみようとした場合、
fakerで生成されたパスワードだと、個人的には入力面倒だな。。。と感じたりするのですが、
その辺りの使い勝手も、良かったら一度検討してみてくださいね。

2021-07-21 00:27 UTC, hsg0830 commented on database/seeds/DatabaseSeeder.php
> +        $this->call(MUserClassificationTableSeeder::class);
シーディングの順序ももう一度考えてみてくださいね。

2021-07-21 10:40 UTC, sukapontan commented on database/migrations/2021_07_18_190716_create_m_user_classifications_table.php
> +            // $table->foreign('id')->references('user_classification_id')->on('m_users');
大変失礼いたしました💦
外部キー制約をかけるテーブルを間違えているのですね…。
こちら、再度外部キー制約について調べつつ修正いたします。
ご指摘いただき、ありがとうございます！

2021-07-21 10:42 UTC, sukapontan commented on database/migrations/2021_07_18_183520_create_m_users_table.php
> +            $table->char('delete_flag', 1);
ご教示いただきありがとうございます！
bool形での実装でもよいのですね！とても勉強になります！

2021-07-21 10:43 UTC, sukapontan commented on database/factories/UserFactory.php
> +        'password' => $faker->password(),
確かにご指摘通りですね…。
考えが浅くて申し訳ありません。
こちらも修正して再度、プッシュいたします。

2021-07-21 10:43 UTC, sukapontan commented on database/seeds/DatabaseSeeder.php
> +        $this->call(MUserClassificationTableSeeder::class);
こちら、承知いたしました！！

2021-07-21 11:48 UTC, sukapontan commented on database/factories/UserFactory.php
> +        'password' => mt_Rand(100000,999999),
パスワードを6桁のランダムな数字に変更してみました。
考慮不足があればご指摘ください。

2021-07-21 11:51 UTC, sukapontan commented on app/User.php
>       *
User.phpの中身となにかの手違いで消してしまっていたので、念のため修正しておきました。

2021-07-22 12:09 UTC, hsg0830 requested changes
お疲れ様です！
パスワードの件だけコメント残しておきましたので、
確認よろしくお願いします！

2021-07-22 12:09 UTC, hsg0830 commented on database/factories/UserFactory.php
> +        'password' => mt_Rand(100000,999999),
そうですね。
僕だと、
`Hash::make('password')`
とかにしますかね。
その方が覚えて、せっかくのダミーデータを使いやすいので^^

2021-07-23 00:45 UTC, merged